using InfiniteTool.GameInterop.EngineDataTypes;
using System.Collections.Generic;

namespace InfiniteTool.GameInterop
{
    public enum InfiniteMap : uint
    {
        Overworld = 0x1,
        WarshipGbraakon = 0xa0b35dce,
        Foundation = 0x2,
        Conservatory = 0x3,
        Spire = 0x4,
        Nexus = 0x5,
        TheCommandSpire = 0x6,
        Repository = 0x7,
        HouseOfReckoning = 0x8,
        SilentAuditorium = 0x9,
    }

    public class InteropConstantData
    {

        public static Dictionary<InfiniteMap, string> MapScenarios = new()
        {
            [InfiniteMap.Overworld] = @"levels\campaign\ring01\island01\island01",
            [InfiniteMap.WarshipGbraakon] = @"levels\campaign\ring01\dungeons\dungeon_banished_ship\dungeon_banished_ship",
            [InfiniteMap.Foundation] = @"levels\campaign\ring01\dungeons\dungeon_underbelly\dungeon_underbelly",
            [InfiniteMap.Conservatory] = @"levels\campaign\ring01\dungeons\dungeon_forerunner_dallas\dungeon_forerunner_dallas",
            [InfiniteMap.Spire] = @"levels\campaign\ring01\dungeons\dungeon_spire_01\dungeon_spire_01",
            [InfiniteMap.Nexus] = @"levels\campaign\ring01\dungeons\dungeon_forerunner_houston\dungeon_forerunner_houston",
            [InfiniteMap.TheCommandSpire] = @"levels\campaign\ring01\dungeons\dungeon_spire_02\dungeon_spire_02",
            [InfiniteMap.Repository] = @"levels\campaign\ring01\dungeons\dungeon_forerunner_austin\dungeon_forerunner_austin",
            [InfiniteMap.HouseOfReckoning] = @"levels\campaign\ring01\dungeons\dungeon_boss_hq_interior\dungeon_boss_hq_interior",
            [InfiniteMap.SilentAuditorium] = @"levels\campaign\ring01\dungeons\dungeon_cortana_palace\dungeon_cortana_palace",
        };

        public static Dictionary<InfiniteMap, string> MapSpawns = new()
        {
            [InfiniteMap.Overworld] = @"streaming",
            [InfiniteMap.WarshipGbraakon] = @"intro_sequence",
            [InfiniteMap.Foundation] = @"from_underbelly",
            [InfiniteMap.Conservatory] = @"forerunner_dallas",
            [InfiniteMap.Spire] = @"",
            [InfiniteMap.Nexus] = @"",
            [InfiniteMap.TheCommandSpire] = @"",
            [InfiniteMap.Repository] = @"",
            [InfiniteMap.HouseOfReckoning] = @"",
            [InfiniteMap.SilentAuditorium] = @"",
        };

		public static Dictionary<string, PersistenceValueType> PersistenceKeys = new()
		{
			["schematic_evade"] = PersistenceValueType.Boolean,
			["schematic_wall"] = PersistenceValueType.Boolean,
			["schematic_sensor"] = PersistenceValueType.Boolean,
			["Schematic-ShieldUpdgrade1"] = PersistenceValueType.Boolean,
			["Schematic-ShieldUpdgrade2"] = PersistenceValueType.Boolean,
			["Schematic-ShieldUpdgrade3"] = PersistenceValueType.Boolean,
			["poi_base_intro_green"] = PersistenceValueType.Byte,
			["poi_fob_ash"] = PersistenceValueType.Byte,
			["poi_fob_aspen"] = PersistenceValueType.Byte,
			["poi_fob_birch"] = PersistenceValueType.Byte,
			["poi_fob_cedar"] = PersistenceValueType.Byte,
			["poi_fob_cherry"] = PersistenceValueType.Byte,
			["poi_fob_dogwood"] = PersistenceValueType.Byte,
			["poi_fob_elm"] = PersistenceValueType.Byte,
			["poi_fob_magnolia"] = PersistenceValueType.Byte,
			["poi_fob_maple"] = PersistenceValueType.Byte,
			["poi_fob_oak"] = PersistenceValueType.Byte,
			["poi_fob_palm"] = PersistenceValueType.Byte,
			["poi_fob_pecan"] = PersistenceValueType.Byte,
			["poi_fob_pine"] = PersistenceValueType.Byte,
			["poi_fob_redwood"] = PersistenceValueType.Byte,
			["poi_fob_sequoia"] = PersistenceValueType.Byte,
			["poi_fob_spruce"] = PersistenceValueType.Byte,
			["poi_fob_willow"] = PersistenceValueType.Byte,
			["poi_outpost_baboon"] = PersistenceValueType.Byte,
			["poi_outpost_gibbon"] = PersistenceValueType.Byte,
			["poi_outpost_howler"] = PersistenceValueType.Byte,
			["poi_outpost_marmoset"] = PersistenceValueType.Byte,
			["poi_outpost_silverback"] = PersistenceValueType.Byte,
			["poi_outpost_mandrill"] = PersistenceValueType.Byte,
			["poi_outpost_bonobo"] = PersistenceValueType.Byte,
			["poi_unsc_alpha"] = PersistenceValueType.Byte,
			["poi_unsc_bravo"] = PersistenceValueType.Byte,
			["poi_unsc_charlie"] = PersistenceValueType.Byte,
			["poi_unsc_delta"] = PersistenceValueType.Byte,
			["poi_unsc_echo"] = PersistenceValueType.Byte,
			["poi_unsc_foxtrot"] = PersistenceValueType.Byte,
			["poi_unsc_golf"] = PersistenceValueType.Byte,
			["poi_unsc_hotel"] = PersistenceValueType.Byte,
			["poi_unsc_india"] = PersistenceValueType.Byte,
			["poi_unsc_juliet"] = PersistenceValueType.Byte,
			["poi_unsc_kilo"] = PersistenceValueType.Byte,
			["poi_unsc_lima"] = PersistenceValueType.Byte,
			["poi_unsc_mike"] = PersistenceValueType.Byte,
			["poi_unsc_november"] = PersistenceValueType.Byte,
			["poi_unsc_oscar"] = PersistenceValueType.Byte,
			["poi_unsc_papa"] = PersistenceValueType.Byte,
			["poi_unsc_quebec"] = PersistenceValueType.Byte,
			["poi_unsc_romeo"] = PersistenceValueType.Byte,
			["poi_unsc_sierra"] = PersistenceValueType.Byte,
			["poi_unsc_tango"] = PersistenceValueType.Byte,
			["poi_boss_aluminum"] = PersistenceValueType.Byte,
			["poi_boss_beryllium"] = PersistenceValueType.Byte,
			["poi_boss_cesium"] = PersistenceValueType.Byte,
			["poi_boss_dubnium"] = PersistenceValueType.Byte,
			["poi_boss_einsteinium"] = PersistenceValueType.Byte,
			["poi_boss_fermium"] = PersistenceValueType.Byte,
			["poi_boss_gallium"] = PersistenceValueType.Byte,
			["poi_boss_helium"] = PersistenceValueType.Byte,
			["poi_boss_iridium"] = PersistenceValueType.Byte,
			["poi_boss_lithium"] = PersistenceValueType.Byte,
			["poi_boss_magnesium"] = PersistenceValueType.Byte,
			["poi_boss_nobelium"] = PersistenceValueType.Byte,
			["poi_boss_osmium"] = PersistenceValueType.Byte,
			["poi_boss_plutonium"] = PersistenceValueType.Byte,
			["poi_boss_radium"] = PersistenceValueType.Byte,
			["poi_bridge_nail"] = PersistenceValueType.Byte,
			["poi_bridge_staple"] = PersistenceValueType.Byte,
			["poi_bridge_screw"] = PersistenceValueType.Byte,
			["poi_bridge_periwinkle"] = PersistenceValueType.Byte,
			["poi_green_pilot_base"] = PersistenceValueType.Byte,
			["poi_green_refinery"] = PersistenceValueType.Byte,
			["poi_green_prison_island"] = PersistenceValueType.Byte,
			["poi_green_prison"] = PersistenceValueType.Byte,
			["poi_green_spire"] = PersistenceValueType.Byte,
			["poi_yellow_spire"] = PersistenceValueType.Byte,
			["poi_boss_hq_exterior"] = PersistenceValueType.Byte,
			["poi_boss_hq_interior"] = PersistenceValueType.Byte,
			["poi_forerunner_tower_main_mission"] = PersistenceValueType.Byte,
			["poi_forerunner_north"] = PersistenceValueType.Byte,
			["poi_forerunner_south"] = PersistenceValueType.Byte,
			["poi_forerunner_east"] = PersistenceValueType.Byte,
			["poi_forerunner_west"] = PersistenceValueType.Byte,
			["poi_forerunner_dallas"] = PersistenceValueType.Byte,
			["poi_forerunner_houston"] = PersistenceValueType.Byte,
			["poi_forerunner_austin"] = PersistenceValueType.Byte,
			["poi_cortana_palace"] = PersistenceValueType.Byte,
			["poi_scanner_afador"] = PersistenceValueType.Byte,
			["poi_scanner_akbash"] = PersistenceValueType.Byte,
			["poi_scanner_akita"] = PersistenceValueType.Byte,
			["poi_scanner_auggie"] = PersistenceValueType.Byte,
			["poi_scanner_barbet"] = PersistenceValueType.Byte,
			["poi_scanner_bassador"] = PersistenceValueType.Byte,
			["poi_scanner_beagle"] = PersistenceValueType.Byte,
			["poi_scanner_borador"] = PersistenceValueType.Byte,
			["poi_scanner_boxer"] = PersistenceValueType.Byte,
			["poi_scanner_bulldog"] = PersistenceValueType.Byte,
			["poi_scanner_cavador"] = PersistenceValueType.Byte,
			["poi_scanner_chihuahua"] = PersistenceValueType.Byte,
			["poi_scanner_collie"] = PersistenceValueType.Byte,
			["poi_scanner_corgi"] = PersistenceValueType.Byte,
			["poi_scanner_dachshund"] = PersistenceValueType.Byte,
			["poi_scanner_dalmatian"] = PersistenceValueType.Byte,
			["poi_scanner_eurasier"] = PersistenceValueType.Byte,
			["poi_scanner_frenchie"] = PersistenceValueType.Byte,
			["poi_scanner_germanshepherd"] = PersistenceValueType.Byte,
			["poi_scanner_goldenretriever"] = PersistenceValueType.Byte,
			["poi_scanner_goldendoodle"] = PersistenceValueType.Byte,
			["poi_scanner_greatdane"] = PersistenceValueType.Byte,
			["poi_scanner_greyhound"] = PersistenceValueType.Byte,
			["poi_scanner_harrier"] = PersistenceValueType.Byte,
			["poi_scanner_havanese"] = PersistenceValueType.Byte,
			["poi_scanner_horgi"] = PersistenceValueType.Byte,
			["poi_scanner_husky"] = PersistenceValueType.Byte,
			["poi_scanner_jackrussell"] = PersistenceValueType.Byte,
			["poi_scanner_komondor"] = PersistenceValueType.Byte,
			["poi_scanner_labrador"] = PersistenceValueType.Byte,
			["poi_scanner_mastiff"] = PersistenceValueType.Byte,
			["poi_scanner_newfoundland"] = PersistenceValueType.Byte,
			["poi_scanner_otterhound"] = PersistenceValueType.Byte,
			["poi_scanner_peekapoo"] = PersistenceValueType.Byte,
			["poi_scanner_pitbull"] = PersistenceValueType.Byte,
			["poi_scanner_poodle"] = PersistenceValueType.Byte,
			["poi_scanner_pug"] = PersistenceValueType.Byte,
			["poi_scanner_rottweiler"] = PersistenceValueType.Byte,
			["poi_scanner_shihtzu"] = PersistenceValueType.Byte,
			["poi_scanner_shibainu"] = PersistenceValueType.Byte,
			["Dungeon-Underbelly"] = PersistenceValueType.Byte,
			["Dungeon-BanishedShip"] = PersistenceValueType.Byte,
			["dungeon_SeedLost"] = PersistenceValueType.Byte,
			["marmoset_AmmoDump01"] = PersistenceValueType.Byte,
			["marmoset_AmmoDump02"] = PersistenceValueType.Byte,
			["marmoset_AmmoDump03"] = PersistenceValueType.Byte,
			["exampleobjective_01"] = PersistenceValueType.Byte,
			["exampleobjective_02"] = PersistenceValueType.Byte,
			["exampleobjective_03"] = PersistenceValueType.Byte,
			["exampleobjective_04"] = PersistenceValueType.Byte,
			["exampleobjective_05"] = PersistenceValueType.Byte,
			["howler_FreeMarines"] = PersistenceValueType.Byte,
			["howler_FreeMarine01"] = PersistenceValueType.Byte,
			["howler_FreeMarine02"] = PersistenceValueType.Byte,
			["howler_FreeMarine03"] = PersistenceValueType.Byte,
			["howler_FreeVIP"] = PersistenceValueType.Byte,
			["silverback_Investigate"] = PersistenceValueType.Byte,
			["silverback_DestroySilos"] = PersistenceValueType.Byte,
			["silverback_DestroyRepairBays"] = PersistenceValueType.Byte,
			["silverback_Silo01"] = PersistenceValueType.Byte,
			["silverback_Silo02"] = PersistenceValueType.Byte,
			["silverback_Silo03"] = PersistenceValueType.Byte,
			["silverback_Silo04"] = PersistenceValueType.Byte,
			["silverback_RepairBay01"] = PersistenceValueType.Byte,
			["silverback_RepairBay02"] = PersistenceValueType.Byte,
			["green_spire_enter"] = PersistenceValueType.Byte,
			["green_spire_hunters"] = PersistenceValueType.Byte,
			["green_spire_investigate"] = PersistenceValueType.Byte,
			["green_spire_follow_monitor"] = PersistenceValueType.Byte,
			["green_spire_deploy_weapon"] = PersistenceValueType.Byte,
			["green_spire_shutdown"] = PersistenceValueType.Byte,
			["green_spire_defeat_boss"] = PersistenceValueType.Byte,
			["green_spire_observation_room_terminal"] = PersistenceValueType.Byte,
			["green_spire_observation_room_door"] = PersistenceValueType.Byte,
			["green_spire_elevator_started"] = PersistenceValueType.Byte,
			["yellow_spire_goto_top"] = PersistenceValueType.Byte,
			["yellow_spire_shutdown"] = PersistenceValueType.Byte,
			["yellow_spire_enter"] = PersistenceValueType.Byte,
			["yellow_spire_collector_room_terminal"] = PersistenceValueType.Byte,
			["yellow_spire_girders_socket"] = PersistenceValueType.Byte,
			["yellow_spire_observation_terminal"] = PersistenceValueType.Byte,
			["yellow_spire_boss_terminal"] = PersistenceValueType.Byte,
			["gibbon_DestroySilos"] = PersistenceValueType.Byte,
			["gibbon_DestroyRepairBays"] = PersistenceValueType.Byte,
			["gibbon_Silo01"] = PersistenceValueType.Byte,
			["gibbon_Silo02"] = PersistenceValueType.Byte,
			["gibbon_Silo03"] = PersistenceValueType.Byte,
			["gibbon_Silo04"] = PersistenceValueType.Byte,
			["gibbon_Silo05"] = PersistenceValueType.Byte,
			["gibbon_RepairBay01"] = PersistenceValueType.Byte,
			["gibbon_RepairBay02"] = PersistenceValueType.Byte,
			["gibbon_RepairBay03"] = PersistenceValueType.Byte,
			["gibbon_RepairBay04"] = PersistenceValueType.Byte,
			["mandrill_Investigate"] = PersistenceValueType.Byte,
			["mandrill_DisableCrane"] = PersistenceValueType.Byte,
			["mandrill_TransportDestroy"] = PersistenceValueType.Byte,
			["mandrill_RaiseSilos"] = PersistenceValueType.Byte,
			["mandrill_Silo01"] = PersistenceValueType.Byte,
			["bonobo_ClearPath"] = PersistenceValueType.Byte,
			["bonobo_Gate01"] = PersistenceValueType.Byte,
			["bonobo_Gate02"] = PersistenceValueType.Byte,
			["bonobo_Gate03"] = PersistenceValueType.Byte,
			["bonobo_switch_hack"] = PersistenceValueType.Byte,
			["bonobo_destroy_power"] = PersistenceValueType.Byte,
			["alpha_kill"] = PersistenceValueType.Byte,
			["bravo_kill"] = PersistenceValueType.Byte,
			["charlie_kill"] = PersistenceValueType.Byte,
			["delta_kill"] = PersistenceValueType.Byte,
			["echo_kill"] = PersistenceValueType.Byte,
			["foxtrot_kill"] = PersistenceValueType.Byte,
			["golf_kill"] = PersistenceValueType.Byte,
			["hotel_kill"] = PersistenceValueType.Byte,
			["india_kill"] = PersistenceValueType.Byte,
			["juliet_kill"] = PersistenceValueType.Byte,
			["kilo_kill"] = PersistenceValueType.Byte,
			["lima_kill"] = PersistenceValueType.Byte,
			["mike_kill"] = PersistenceValueType.Byte,
			["november_kill"] = PersistenceValueType.Byte,
			["oscar_kill"] = PersistenceValueType.Byte,
			["papa_kill"] = PersistenceValueType.Byte,
			["quebec_kill"] = PersistenceValueType.Byte,
			["romeo_kill"] = PersistenceValueType.Byte,
			["sierra_kill"] = PersistenceValueType.Byte,
			["tango_kill"] = PersistenceValueType.Byte,
			["aluminum_kill"] = PersistenceValueType.Byte,
			["beryllium_kill"] = PersistenceValueType.Byte,
			["cesium_kill"] = PersistenceValueType.Byte,
			["dubnium_kill"] = PersistenceValueType.Byte,
			["einsteinium_kill"] = PersistenceValueType.Byte,
			["fermium_kill"] = PersistenceValueType.Byte,
			["gallium_kill"] = PersistenceValueType.Byte,
			["helium_kill"] = PersistenceValueType.Byte,
			["iridium_kill"] = PersistenceValueType.Byte,
			["lithium_kill"] = PersistenceValueType.Byte,
			["magnesium_kill"] = PersistenceValueType.Byte,
			["nobelium_kill"] = PersistenceValueType.Byte,
			["osmium_kill"] = PersistenceValueType.Byte,
			["plutonium_kill"] = PersistenceValueType.Byte,
			["radium_kill"] = PersistenceValueType.Byte,
			["pilotbase_cylix_seen"] = PersistenceValueType.Boolean,
			["pilotbase_reunite"] = PersistenceValueType.Byte,
			["pilotbase_gantry"] = PersistenceValueType.Byte,
			["pilotbase_terminal"] = PersistenceValueType.Byte,
			["pilotbase_murdergate"] = PersistenceValueType.Byte,
			["pilotbase_dock_terminal"] = PersistenceValueType.Byte,
			["pilotbase_dock_pelican"] = PersistenceValueType.Byte,
			["pilotbase_game_finished_vo"] = PersistenceValueType.Boolean,
			["pris_island_complete_prison"] = PersistenceValueType.Byte,
			["pris_island_complete_fob"] = PersistenceValueType.Byte,
			["pris_investigate"] = PersistenceValueType.Byte,
			["pris_locate_signal_1"] = PersistenceValueType.Byte,
			["pris_enter_prison"] = PersistenceValueType.Byte,
			["pris_end_lockdown"] = PersistenceValueType.Byte,
			["pris_power_gravlift"] = PersistenceValueType.Byte,
			["pris_fight_reinforcements"] = PersistenceValueType.Byte,
			["pris_loc_sensor"] = PersistenceValueType.Byte,
			["pris_locate_signal_2"] = PersistenceValueType.Byte,
			["pris_rescue_spartan"] = PersistenceValueType.Byte,
			["pris_defeat_chak_lok"] = PersistenceValueType.Byte,
			["prison_bridge"] = PersistenceValueType.Byte,
			["banishedship_DeactivateCannon"] = PersistenceValueType.Byte,
			["banishedship_LocateBridge"] = PersistenceValueType.Byte,
			["banishedship_ScupperShip"] = PersistenceValueType.Byte,
			["banishedship_DestroyManifold_01"] = PersistenceValueType.Byte,
			["banishedship_DestroyManifold_02"] = PersistenceValueType.Byte,
			["banishedship_OverloadEngines"] = PersistenceValueType.Byte,
			["banishedship_EscapeToPelican"] = PersistenceValueType.Byte,
			["banishedship_GrappleToPelican"] = PersistenceValueType.Byte,
			["banishedship_OverrideEngines"] = PersistenceValueType.Byte,
			["banishedship_PingTutorial"] = PersistenceValueType.Boolean,
			["banishedship_GrappleTutorial"] = PersistenceValueType.Boolean,
			["banishedship_ArmoryTwoDirectivesCompleted"] = PersistenceValueType.Boolean,
			["banishedship_BridgeKilledAllEnemies"] = PersistenceValueType.Boolean,
			["underbelly_locate_weapon"] = PersistenceValueType.Byte,
			["underbelly_get_index"] = PersistenceValueType.Byte,
			["underbelly_reach_surface"] = PersistenceValueType.Byte,
			["underbelly_investigate_dead_spartan_stone"] = PersistenceValueType.Byte,
			["underbelly_temple_socket"] = PersistenceValueType.Byte,
			["underbelly_temple_terminal"] = PersistenceValueType.Byte,
			["underbelly_defeat_tremonious"] = PersistenceValueType.Byte,
			["underbelly_index_terminal"] = PersistenceValueType.Byte,
			["underbelly_defend_middle_terminal"] = PersistenceValueType.Byte,
			["underbelly_grav_lift_socket"] = PersistenceValueType.Byte,
			["underbelly_temple_bloodgate_and_terminal"] = PersistenceValueType.Byte,
			["underbelly_temple_socket_waypoint"] = PersistenceValueType.Byte,
			["underbelly_temple_cradle_waypoint"] = PersistenceValueType.Byte,
			["underbelly_campfire_cathedral"] = PersistenceValueType.Byte,
			["underbelly_campfire_cortana_exit"] = PersistenceValueType.Byte,
			["underbelly_campfire_temple"] = PersistenceValueType.Byte,
			["refine_goto_refinery"] = PersistenceValueType.Byte,
			["refine_find"] = PersistenceValueType.Byte,
			["refine_descend"] = PersistenceValueType.Byte,
			["refine_disable_laser"] = PersistenceValueType.Byte,
			["refine_overload_regs"] = PersistenceValueType.Byte,
			["refine_interact_regulator_1"] = PersistenceValueType.Byte,
			["refine_disable_regulator_1"] = PersistenceValueType.Byte,
			["refine_disable_cooling_pylons_1_1"] = PersistenceValueType.Byte,
			["refine_disable_cooling_pylons_1_2"] = PersistenceValueType.Byte,
			["refine_interact_regulator_2"] = PersistenceValueType.Byte,
			["refine_disable_regulator_2"] = PersistenceValueType.Byte,
			["refine_disable_cooling_pylons_2_1"] = PersistenceValueType.Byte,
			["refine_disable_cooling_pylons_2_2"] = PersistenceValueType.Byte,
			["refine_com_room_return"] = PersistenceValueType.Byte,
			["refine_disable_laser2"] = PersistenceValueType.Byte,
			["refine_defeat_bassman"] = PersistenceValueType.Byte,
			["refine_goto_laser_hole"] = PersistenceValueType.Byte,
			["refine_goto_dungeon"] = PersistenceValueType.Byte,
			["poi_base_aa_island"] = PersistenceValueType.Byte,
			["aa_island_gun_east"] = PersistenceValueType.Byte,
			["aa_island_gun_east_icon"] = PersistenceValueType.Byte,
			["aa_island_gun_north"] = PersistenceValueType.Byte,
			["aa_island_gun_north_icon"] = PersistenceValueType.Byte,
			["aa_island_gun_west"] = PersistenceValueType.Byte,
			["aa_island_gun_west_icon"] = PersistenceValueType.Byte,
			["aa_island_return_pelican"] = PersistenceValueType.Byte,
			["aa_island_defeat_spartan_killers"] = PersistenceValueType.Byte,
			["aa_island_locate_pilot"] = PersistenceValueType.Byte,
			["boss_hq_exterior_extend_bridge"] = PersistenceValueType.Byte,
			["boss_hq_exterior_exit"] = PersistenceValueType.Byte,
			["boss_hq_interior_challenge_01"] = PersistenceValueType.Byte,
			["boss_hq_interior_challenge_02"] = PersistenceValueType.Byte,
			["boss_hq_interior_reach_03"] = PersistenceValueType.Byte,
			["boss_hq_interior_spartan_killer"] = PersistenceValueType.Byte,
			["boss_hq_interior_boss_time"] = PersistenceValueType.Byte,
			["boss_hq_interior_freedom"] = PersistenceValueType.Byte,
			["boss_hq_interior_hotdog_01"] = PersistenceValueType.Byte,
			["boss_hq_interior_hotdog_02"] = PersistenceValueType.Byte,
			["boss_hq_interior_hotdog_03"] = PersistenceValueType.Byte,
			["boss_hq_interior_hotdog_04"] = PersistenceValueType.Byte,
			["boss_hq_interior_challenge_waypoint"] = PersistenceValueType.Byte,
			["boss_hq_interior_try_free_pilot"] = PersistenceValueType.Byte,
			["cortana_palace_get_to_boss"] = PersistenceValueType.Byte,
			["cortana_palace_retrieve_weapon"] = PersistenceValueType.Byte,
			["cortana_palace_stop_boss"] = PersistenceValueType.Byte,
			["cortana_palace_escape"] = PersistenceValueType.Byte,
			["cortana_palace_judgementroom_elevator"] = PersistenceValueType.Byte,
			["cortana_palace_dropsite_terminal"] = PersistenceValueType.Byte,
			["cortana_palace_entrancehallsaccess_socket"] = PersistenceValueType.Byte,
			["cortana_palace_atrium_terminal"] = PersistenceValueType.Byte,
			["cortana_palace_atrium_exitdoor"] = PersistenceValueType.Byte,
			["cortana_palace_cortana_room_2_terminal"] = PersistenceValueType.Byte,
			["cortana_palace_cortana_room_2_cutscene"] = PersistenceValueType.Byte,
			["cortana_palace_sentinelroom_exitdoor"] = PersistenceValueType.Byte,
			["cortana_palace_cortana_room_3_elevator"] = PersistenceValueType.Byte,
			["cortana_palace_judgmentroom_terminal"] = PersistenceValueType.Byte,
			["poi_fob_aspen_capture"] = PersistenceValueType.Byte,
			["poi_fob_birch_capture"] = PersistenceValueType.Byte,
			["poi_fob_cherry_capture"] = PersistenceValueType.Byte,
			["poi_fob_dogwood_capture"] = PersistenceValueType.Byte,
			["poi_fob_elm_capture"] = PersistenceValueType.Byte,
			["poi_fob_maple_capture"] = PersistenceValueType.Byte,
			["poi_fob_oak_capture"] = PersistenceValueType.Byte,
			["poi_fob_palm_capture"] = PersistenceValueType.Byte,
			["poi_fob_pecan_capture"] = PersistenceValueType.Byte,
			["poi_fob_pine_capture"] = PersistenceValueType.Byte,
			["poi_fob_redwood_capture"] = PersistenceValueType.Byte,
			["poi_fob_sequoia_capture"] = PersistenceValueType.Byte,
			["poi_fob_spruce_capture"] = PersistenceValueType.Byte,
			["poi_fob_willow_capture"] = PersistenceValueType.Byte,
			["nar_towers_initialized"] = PersistenceValueType.Boolean,
			["tower_forerunner_north"] = PersistenceValueType.Byte,
			["tower_forerunner_south"] = PersistenceValueType.Byte,
			["tower_forerunner_east"] = PersistenceValueType.Byte,
			["tower_forerunner_west"] = PersistenceValueType.Byte,
			["baboon_EndLockdown"] = PersistenceValueType.Byte,
			["baboon_ExposePanels"] = PersistenceValueType.Byte,
			["baboon_DestroyGenerators"] = PersistenceValueType.Byte,
			["baboon_generator01"] = PersistenceValueType.Byte,
			["baboon_generator02"] = PersistenceValueType.Byte,
			["baboon_generator03"] = PersistenceValueType.Byte,
			["baboon_generator04"] = PersistenceValueType.Byte,
			["baboon_discoveredNarrative"] = PersistenceValueType.Byte,
			["baboon_lockdownNarrative"] = PersistenceValueType.Byte,
			["baboon_commsArrayReinforcements"] = PersistenceValueType.Byte,
			["dallas_digsite_complete"] = PersistenceValueType.Byte,
			["dallas_investigate_conservatory"] = PersistenceValueType.Byte,
			["dallas_investigate_dead_spartan_makovich"] = PersistenceValueType.Byte,
			["dallas_locate_pyre"] = PersistenceValueType.Byte,
			["dallas_survive_ambush"] = PersistenceValueType.Byte,
			["dallas_retrieve_weapon"] = PersistenceValueType.Byte,
			["dallas_investigate_dead_spartan_sorel"] = PersistenceValueType.Byte,
			["dallas_invisible_guilty_a"] = PersistenceValueType.Byte,
			["dallas_invisible_guilty_b_01"] = PersistenceValueType.Byte,
			["dallas_invisible_guilty_b_02"] = PersistenceValueType.Byte,
			["dallas_invisible_guilty_b_all"] = PersistenceValueType.Byte,
			["dallas_elbow_one"] = PersistenceValueType.Byte,
			["dallas_elbow_two"] = PersistenceValueType.Byte,
			["dallas_invisible_drop_down"] = PersistenceValueType.Byte,
			["dallas_invisible_drop_fight_done"] = PersistenceValueType.Byte,
			["dallas_elbow_three"] = PersistenceValueType.Byte,
			["dallas_elbow_four"] = PersistenceValueType.Byte,
			["dallas_conservatory_check"] = PersistenceValueType.Byte,
			["dallas_investigate_cradle"] = PersistenceValueType.Byte,
			["dallas_call_elevator"] = PersistenceValueType.Byte,
			["dallas_invisible_control_elevator_ready"] = PersistenceValueType.Byte,
			["dallas_campfire_observation"] = PersistenceValueType.Byte,
			["dallas_campfire_dropdown"] = PersistenceValueType.Byte,
			["dallas_campfire_ribcage"] = PersistenceValueType.Byte,
			["dallas_elevator_started"] = PersistenceValueType.Byte,
			["dallas_interior"] = PersistenceValueType.Byte,
			["houston_find_entrance"] = PersistenceValueType.Byte,
			["houston_power_gravlift"] = PersistenceValueType.Byte,
			["houston_nexus_south"] = PersistenceValueType.Byte,
			["houston_nexus_west"] = PersistenceValueType.Byte,
			["houston_nexus_north"] = PersistenceValueType.Byte,
			["houston_nexus_east"] = PersistenceValueType.Byte,
			["houston_nexus_terminal_entry"] = PersistenceValueType.Byte,
			["houston_nexus_terminal_end"] = PersistenceValueType.Byte,
			["houston_piston_terminal"] = PersistenceValueType.Byte,
			["houston_gondola_terminal"] = PersistenceValueType.Byte,
			["houston_plaza_terminal"] = PersistenceValueType.Byte,
			["houston_nexus_west_cradle"] = PersistenceValueType.Boolean,
			["houston_nexus_north_cradle"] = PersistenceValueType.Boolean,
			["houston_nexus_east_cradle"] = PersistenceValueType.Boolean,
			["austin_invisible_index_mirrored_plinth"] = PersistenceValueType.Byte,
			["austin_rescue_pilot"] = PersistenceValueType.Byte,
			["austin_escape_dungeon"] = PersistenceValueType.Byte,
			["austin_activate_lift"] = PersistenceValueType.Byte,
			["austin_activate_lift01"] = PersistenceValueType.Byte,
			["austin_activate_lift02"] = PersistenceValueType.Byte,
			["austin_skull_capacitor"] = PersistenceValueType.Boolean,
			["austin_find_plinth"] = PersistenceValueType.Byte,
			["austin_invisible_gravlift_a_plinth"] = PersistenceValueType.Byte,
			["austin_invisible_chapel_split"] = PersistenceValueType.Byte,
			["austin_invisible_chapel_east"] = PersistenceValueType.Byte,
			["austin_invisible_chapel_west"] = PersistenceValueType.Byte,
			["austin_invisible_chapel_gravlift"] = PersistenceValueType.Byte,
			["austin_invisible_gravlift_b_plinth"] = PersistenceValueType.Byte,
			["austin_invisible_final"] = PersistenceValueType.Byte,
			["austin_invisible_final_second_door"] = PersistenceValueType.Byte,
			["austin_index_mirrored_plinth_bloodgate"] = PersistenceValueType.Byte,
			["austin_campfire_canopy_vista"] = PersistenceValueType.Byte,
			["austin_campfire_chapel_entry"] = PersistenceValueType.Byte,
			["austin_airlock_entered"] = PersistenceValueType.Byte,
			["poi_periwinkle"] = PersistenceValueType.Byte,
			["aa_island_enter_pelican"] = PersistenceValueType.Byte,
			["periwinkle_houston_arrival"] = PersistenceValueType.Byte,
			["periwinkle_arrival"] = PersistenceValueType.Byte,
			["periwinkle_arrival_plinth_nseq_complete"] = PersistenceValueType.Boolean,
			["periwinkle_spire_key"] = PersistenceValueType.Byte,
			["periwinkle_houston_waypoints"] = PersistenceValueType.Byte,
			["periwinkle_houston_return"] = PersistenceValueType.Byte,
			["fr_main_first_key"] = PersistenceValueType.Byte,
			["fr_main_all_keys"] = PersistenceValueType.Byte,
			["fr_main_north_tracker"] = PersistenceValueType.Byte,
			["fr_main_south_tracker"] = PersistenceValueType.Byte,
			["fr_main_east_tracker"] = PersistenceValueType.Byte,
			["fr_main_west_tracker"] = PersistenceValueType.Byte,
			["fr_north_enter_area"] = PersistenceValueType.Byte,
			["fr_north_hack_terminal"] = PersistenceValueType.Byte,
			["fr_north_key_switch"] = PersistenceValueType.Byte,
			["fr_south_enter_area"] = PersistenceValueType.Byte,
			["fr_south_hack_terminal"] = PersistenceValueType.Byte,
			["fr_south_key_switch"] = PersistenceValueType.Byte,
			["fr_east_enter_area"] = PersistenceValueType.Byte,
			["fr_east_hack_terminal"] = PersistenceValueType.Byte,
			["fr_east_key_switch"] = PersistenceValueType.Byte,
			["fr_west_enter_area"] = PersistenceValueType.Byte,
			["fr_west_hack_terminal"] = PersistenceValueType.Byte,
			["fr_west_key_switch"] = PersistenceValueType.Byte,
			["Loadout-IsValid"] = PersistenceValueType.Boolean,
			["Loadout-FirstWeaponExists"] = PersistenceValueType.Boolean,
			["Loadout-FirstWeaponTag"] = PersistenceValueType.Long,
			["Loadout-FirstWeaponConfigTag"] = PersistenceValueType.Long,
			["Loadout-FirstWeaponVariant"] = PersistenceValueType.Long,
			["Loadout-FirstWeaponAmmoLoaded"] = PersistenceValueType.Long,
			["Loadout-FirstWeaponTotalAmmo"] = PersistenceValueType.Long,
			["Loadout-FirstWeaponAge"] = PersistenceValueType.Byte,
			["Loadout-SecondWeaponExists"] = PersistenceValueType.Boolean,
			["Loadout-SecondWeaponTag"] = PersistenceValueType.Long,
			["Loadout-SecondWeaponConfigTag"] = PersistenceValueType.Long,
			["Loadout-SecondWeaponVariant"] = PersistenceValueType.Long,
			["Loadout-SecondWeaponAmmoLoaded"] = PersistenceValueType.Long,
			["Loadout-SecondWeaponTotalAmmo"] = PersistenceValueType.Long,
			["Loadout-SecondWeaponAge"] = PersistenceValueType.Byte,
			["Loadout-ThirdWeaponExists"] = PersistenceValueType.Boolean,
			["Loadout-ThirdWeaponTag"] = PersistenceValueType.Long,
			["Loadout-ThirdWeaponConfigTag"] = PersistenceValueType.Long,
			["Loadout-ThirdWeaponVariant"] = PersistenceValueType.Long,
			["Loadout-ThirdWeaponAmmoLoaded"] = PersistenceValueType.Long,
			["Loadout-ThirdWeaponTotalAmmo"] = PersistenceValueType.Long,
			["Loadout-ThirdWeaponAge"] = PersistenceValueType.Byte,
			["Loadout-FourthWeaponExists"] = PersistenceValueType.Boolean,
			["Loadout-FourthWeaponTag"] = PersistenceValueType.Long,
			["Loadout-FourthWeaponConfigTag"] = PersistenceValueType.Long,
			["Loadout-FourthWeaponVariant"] = PersistenceValueType.Long,
			["Loadout-FourthWeaponAmmoLoaded"] = PersistenceValueType.Long,
			["Loadout-FourthWeaponTotalAmmo"] = PersistenceValueType.Long,
			["Loadout-FourthWeaponAge"] = PersistenceValueType.Byte,
			["Loadout-FirstGrenadeExists"] = PersistenceValueType.Boolean,
			["Loadout-FirstGrenadeType"] = PersistenceValueType.Byte,
			["Loadout-FirstGrenadeCount"] = PersistenceValueType.Byte,
			["Loadout-SecondGrenadeExists"] = PersistenceValueType.Boolean,
			["Loadout-SecondGrenadeType"] = PersistenceValueType.Byte,
			["Loadout-SecondGrenadeCount"] = PersistenceValueType.Byte,
			["Loadout-ThirdGrenadeExists"] = PersistenceValueType.Boolean,
			["Loadout-ThirdGrenadeType"] = PersistenceValueType.Byte,
			["Loadout-ThirdGrenadeCount"] = PersistenceValueType.Byte,
			["Loadout-FourthGrenadeExists"] = PersistenceValueType.Boolean,
			["Loadout-FourthGrenadeType"] = PersistenceValueType.Byte,
			["Loadout-FourthGrenadeCount"] = PersistenceValueType.Byte,
			["Loadout-InputSlotsValid"] = PersistenceValueType.Boolean,
			["Loadout-FirstInputSlotTag"] = PersistenceValueType.Long,
			["Loadout-FirstInputSlotEnergy"] = PersistenceValueType.Byte,
			["Loadout-FirstInputSlotEnergyDelay"] = PersistenceValueType.Byte,
			["Loadout-SecondInputSlotTag"] = PersistenceValueType.Long,
			["Loadout-SecondInputSlotEnergy"] = PersistenceValueType.Byte,
			["Loadout-SecondInputSlotEnergyDelay"] = PersistenceValueType.Byte,
			["Loadout-ThirdInputSlotTag"] = PersistenceValueType.Long,
			["Loadout-ThirdInputSlotEnergy"] = PersistenceValueType.Byte,
			["Loadout-ThirdInputSlotEnergyDelay"] = PersistenceValueType.Byte,
			["Loadout-SupplyEnergy"] = PersistenceValueType.Long,
			["tod_current_time"] = PersistenceValueType.Byte,
			["tod_lock_time"] = PersistenceValueType.Boolean,
			["nar_ref_extractor_seen"] = PersistenceValueType.Boolean,
			["nar_ref_antigonum_hologram_seen"] = PersistenceValueType.Boolean,
			["nar_ref_extractor_console_activated"] = PersistenceValueType.Boolean,
			["nar_ref_destroyed_pylon_any_base"] = PersistenceValueType.Boolean,
			["nar_ref_destroyed_all_plyons_any_base"] = PersistenceValueType.Boolean,
			["nar_ref_venting_reset"] = PersistenceValueType.Boolean,
			["nar_ref_control_room_console_activated"] = PersistenceValueType.Boolean,
			["nar_ref_unscevent_capturedmar_first_seen"] = PersistenceValueType.Boolean,
			["nar_ref_mongoose_first_summon"] = PersistenceValueType.Boolean,
			["nar_ref_gungoose_first_summon"] = PersistenceValueType.Boolean,
			["nar_ref_warthog_first_summon"] = PersistenceValueType.Boolean,
			["nar_ref_rockethog_first_summon"] = PersistenceValueType.Boolean,
			["nar_ref_rallyhog_first_summon"] = PersistenceValueType.Boolean,
			["nar_ref_scorpion_first_summon"] = PersistenceValueType.Boolean,
			["nar_ref_wasp_first_summon"] = PersistenceValueType.Boolean,
			["FirstVehicleExists"] = PersistenceValueType.Boolean,
			["FirstVehicleBSP"] = PersistenceValueType.Long,
			["FirstVehicleTag"] = PersistenceValueType.Long,
			["FirstVehicleConfigTag"] = PersistenceValueType.Long,
			["FirstVehicleVariant"] = PersistenceValueType.Long,
			["FirstVehicleLocationX"] = PersistenceValueType.Long,
			["FirstVehicleLocationY"] = PersistenceValueType.Long,
			["FirstVehicleLocationZ"] = PersistenceValueType.Long,
			["FirstVehicleFacingX"] = PersistenceValueType.Long,
			["FirstVehicleFacingY"] = PersistenceValueType.Long,
			["FirstVehicleFacingZ"] = PersistenceValueType.Long,
			["SecondVehicleExists"] = PersistenceValueType.Boolean,
			["SecondVehicleBSP"] = PersistenceValueType.Long,
			["SecondVehicleTag"] = PersistenceValueType.Long,
			["SecondVehicleConfigTag"] = PersistenceValueType.Long,
			["SecondVehicleVariant"] = PersistenceValueType.Long,
			["SecondVehicleLocationX"] = PersistenceValueType.Long,
			["SecondVehicleLocationY"] = PersistenceValueType.Long,
			["SecondVehicleLocationZ"] = PersistenceValueType.Long,
			["SecondVehicleFacingX"] = PersistenceValueType.Long,
			["SecondVehicleFacingY"] = PersistenceValueType.Long,
			["SecondVehicleFacingZ"] = PersistenceValueType.Long,
			["Valor-Points"] = PersistenceValueType.Long,
			["valor_reward_read_mongoose"] = PersistenceValueType.Boolean,
			["valor_reward_read_sidearm_pistol"] = PersistenceValueType.Boolean,
			["valor_reward_read_assault_rifle"] = PersistenceValueType.Boolean,
			["valor_reward_read_AssaultRifleMarine"] = PersistenceValueType.Boolean,
			["valor_reward_read_razorbackhog"] = PersistenceValueType.Boolean,
			["valor_reward_read_frag_grenade"] = PersistenceValueType.Boolean,
			["valor_reward_read_combat_shotgun"] = PersistenceValueType.Boolean,
			["valor_reward_read_CombatShotgunMarine"] = PersistenceValueType.Boolean,
			["valor_reward_read_warthog"] = PersistenceValueType.Boolean,
			["valor_reward_read_commando_rifle"] = PersistenceValueType.Boolean,
			["valor_reward_read_CommandoRifleMarine"] = PersistenceValueType.Boolean,
			["valor_reward_read_battle_rifle"] = PersistenceValueType.Boolean,
			["valor_reward_read_BattleRifleMarine"] = PersistenceValueType.Boolean,
			["valor_reward_read_gungoose"] = PersistenceValueType.Boolean,
			["valor_reward_read_sniper_rifle"] = PersistenceValueType.Boolean,
			["valor_reward_read_SniperRifleMarine"] = PersistenceValueType.Boolean,
			["valor_reward_read_spnkr_rocket_launcher"] = PersistenceValueType.Boolean,
			["valor_reward_read_RocketLauncherMarine"] = PersistenceValueType.Boolean,
			["valor_reward_read_scorpion"] = PersistenceValueType.Boolean,
			["valor_reward_read_mlrs"] = PersistenceValueType.Boolean,
			["valor_reward_read_sidearm_pistol_elite"] = PersistenceValueType.Boolean,
			["valor_reward_read_assault_rifle_tactical"] = PersistenceValueType.Boolean,
			["valor_reward_read_combat_shotgun_choke"] = PersistenceValueType.Boolean,
			["valor_reward_read_wasp"] = PersistenceValueType.Boolean,
			["valor_reward_read_commando_rifle_suburban"] = PersistenceValueType.Boolean,
			["valor_reward_read_br_scout"] = PersistenceValueType.Boolean,
			["valor_reward_read_sniper_rifle_dmr"] = PersistenceValueType.Boolean,
			["valor_reward_read_hydra_surgical_strike"] = PersistenceValueType.Boolean,
			["valor_reward_read_rockethog"] = PersistenceValueType.Boolean,
			["valor_reward_read_sword_striker"] = PersistenceValueType.Boolean,
			["valor_reward_read_hammer_frontlines"] = PersistenceValueType.Boolean,
			["valor_reward_read_arc_zapper"] = PersistenceValueType.Boolean,
			["valor_reward_read_spike_revolver"] = PersistenceValueType.Boolean,
			["valor_reward_read_plasma_pistol_unbound"] = PersistenceValueType.Boolean,
			["valor_reward_read_needler_seeker"] = PersistenceValueType.Boolean,
			["valor_reward_read_skewer_explosive"] = PersistenceValueType.Boolean,
			["valor_reward_read_hotrod_gun_smartbounce"] = PersistenceValueType.Boolean,
			["valor_reward_read_volt_action_overclocked"] = PersistenceValueType.Boolean,
			["valor_reward_read_heatwave_overcooked"] = PersistenceValueType.Boolean,
			["valor_reward_read_plasma_wetwork_auto"] = PersistenceValueType.Boolean,
			["valor_reward_read_plasma_plasmablaster_commando"] = PersistenceValueType.Boolean,
			["valor_reward_read_provoker_bouncing"] = PersistenceValueType.Boolean,
			["valor_reward_read_hardlight_sentinel_beam_heatrod"] = PersistenceValueType.Boolean,
			["valor_reward_read_spnker_rocket_launcher_tracking"] = PersistenceValueType.Boolean,
			["valor_reward_read_escharums_axe_gravity_hammer"] = PersistenceValueType.Boolean,
			["valor_reward_read_jega_energy_sword"] = PersistenceValueType.Boolean,
			["Achievement_01_AintAfraidOfNoGhost"] = PersistenceValueType.Boolean,
			["Achievement_02_TheresTwoOfYouNow"] = PersistenceValueType.Boolean,
			["Achievement_03_StrongFoundations"] = PersistenceValueType.Boolean,
			["Achievement_04_RingReverie"] = PersistenceValueType.Boolean,
			["Achievement_05_TowerStruggle"] = PersistenceValueType.Boolean,
			["Achievement_06_CanYouDigIt"] = PersistenceValueType.Boolean,
			["Achievement_08_MoreLikeExSpire"] = PersistenceValueType.Boolean,
			["Achievement_09_BatteryNotIncluded"] = PersistenceValueType.Boolean,
			["Achievement_10_BrothersGrim"] = PersistenceValueType.Boolean,
			["Achievement_12_WhatWillItTake"] = PersistenceValueType.Boolean,
			["Achievement_13_HoldThatThought"] = PersistenceValueType.Boolean,
			["Achievement_15_HouseParty"] = PersistenceValueType.Boolean,
			["Achievement_16_EchoLocation"] = PersistenceValueType.Boolean,
			["Achievement_17_EndlessPossibilities"] = PersistenceValueType.Boolean,
			["Achievement_55_MixThingsUpToShootYourWayOut"] = PersistenceValueType.Boolean,
			["Achievement_56_StickAround"] = PersistenceValueType.Boolean,
			["Achievement_57_GotTheDrop"] = PersistenceValueType.Boolean,
			["Achievement_58_ToughWayToGo"] = PersistenceValueType.Boolean,
			["Achievement_59_PowerDrill"] = PersistenceValueType.Boolean,
			["Achievement_60_ConservationOfMomentum"] = PersistenceValueType.Boolean,
			["Achievement_60_ConservationOfMomentum_Start"] = PersistenceValueType.Long,
			["Achievement_61_WildWeasel"] = PersistenceValueType.Boolean,
			["Achievement_61_WildWeasel_Start"] = PersistenceValueType.Long,
			["Achievement_62_ItReallyDoesBeatAnything"] = PersistenceValueType.Boolean,
			["Achievement_63_Backstabber"] = PersistenceValueType.Boolean,
			["Achievement_64_ReckoningAtRange"] = PersistenceValueType.Boolean,
			["Achievement_65_TurnaboutIsFairPlay"] = PersistenceValueType.Boolean,
			["Achievement_66_WhosTheBoss"] = PersistenceValueType.Boolean,
			["Achievement_67_BreachingWithBrevity"] = PersistenceValueType.Boolean,
			["Achievement_67_BreachingWithBrevity_Start"] = PersistenceValueType.Long,
			["Achievement_68_ForzaVeloce"] = PersistenceValueType.Boolean,
			["Achievement_69_PassingTheGas"] = PersistenceValueType.Boolean,
			["Achievement_70_ThatsItYouPeaked"] = PersistenceValueType.Boolean,
			["Achievement_75_WhipRidingTheGhost"] = PersistenceValueType.Boolean,
			["Achievement_77_BringShielaHomeSafely"] = PersistenceValueType.Boolean,
			["Achievement_78_TakesOneToMakeOne"] = PersistenceValueType.Boolean,
			["Achievement_79_ThoughtWeCouldUseSomeBackup"] = PersistenceValueType.Boolean,
			["Equipment_Points"] = PersistenceValueType.Long,
			["Grapple_Upgrade_Level"] = PersistenceValueType.Byte,
			["Evade_Upgrade_Level"] = PersistenceValueType.Byte,
			["Wall_Upgrade_Level"] = PersistenceValueType.Byte,
			["Sensor_Upgrade_Level"] = PersistenceValueType.Byte,
			["Shield_Upgrade_Level"] = PersistenceValueType.Byte,
			["Grapple_Upgrade_Read_Level"] = PersistenceValueType.Byte,
			["Evade_Upgrade_Read_Level"] = PersistenceValueType.Byte,
			["Wall_Upgrade_Read_Level"] = PersistenceValueType.Byte,
			["Sensor_Upgrade_Read_Level"] = PersistenceValueType.Byte,
			["Shield_Upgrade_Read_Level"] = PersistenceValueType.Byte,
			["Grapple-Use-Count"] = PersistenceValueType.Long,
			["Wall-Use-Count"] = PersistenceValueType.Long,
			["Sensor-Use-Count"] = PersistenceValueType.Long,
			["Evade-Use-Count"] = PersistenceValueType.Long,
			["Visor-Use-Count"] = PersistenceValueType.Long,
			["StatSecondsPlayed"] = PersistenceValueType.Long,
			["StatFusionCoilsThrown"] = PersistenceValueType.Long,
			["StatFlocksKilled"] = PersistenceValueType.Long,
			["StatGruntsLaunchedKilled"] = PersistenceValueType.Long,
			["StatFragGrenadeKills"] = PersistenceValueType.Long,
			["StatPlasmaGrenadeKills"] = PersistenceValueType.Long,
			["StatLightningGrenadeKills"] = PersistenceValueType.Long,
			["StatSpikeGrenadeKills"] = PersistenceValueType.Long,
			["StatSidearmPistolKills"] = PersistenceValueType.Long,
			["StatMagnumKills"] = PersistenceValueType.Long,
			["StatShotgunKills"] = PersistenceValueType.Long,
			["StatSMGKills"] = PersistenceValueType.Long,
			["StatAssaultRifleKills"] = PersistenceValueType.Long,
			["StatBattleRifleKills"] = PersistenceValueType.Long,
			["StatVakara78Kills"] = PersistenceValueType.Long,
			["StatDMRKills"] = PersistenceValueType.Long,
			["StatSawKills"] = PersistenceValueType.Long,
			["StatSniperRifleKills"] = PersistenceValueType.Long,
			["StatReachGrenadeLauncherKills"] = PersistenceValueType.Long,
			["StatRailGunKills"] = PersistenceValueType.Long,
			["StatSpartanLaserKills"] = PersistenceValueType.Long,
			["StatCovenantCarbineKills"] = PersistenceValueType.Long,
			["StatStormRifleKills"] = PersistenceValueType.Long,
			["StatBeamRifleKills"] = PersistenceValueType.Long,
			["StatNeedlerKills"] = PersistenceValueType.Long,
			["StatPlasmaPistolKills"] = PersistenceValueType.Long,
			["StatEnergySwordKills"] = PersistenceValueType.Long,
			["StatFuelRodCannonKills"] = PersistenceValueType.Long,
			["StatCovenantGrenadeLauncherKills"] = PersistenceValueType.Long,
			["StatGravityHammerKills"] = PersistenceValueType.Long,
			["StatBeamRifleH2Kills"] = PersistenceValueType.Long,
			["StatPlasmaRifleKills"] = PersistenceValueType.Long,
			["StatSpikerKills"] = PersistenceValueType.Long,
			["StatGatlingMortarKills"] = PersistenceValueType.Long,
			["StatBeltFedMachineGunKills"] = PersistenceValueType.Long,
			["StatCombatShotgunKills"] = PersistenceValueType.Long,
			["StatCommandoRifleKills"] = PersistenceValueType.Long,
			["StatDoubleBarrelShotgunKills"] = PersistenceValueType.Long,
			["StatHeatwaveKills"] = PersistenceValueType.Long,
			["StatHotrodKills"] = PersistenceValueType.Long,
			["StatLiquidatorKills"] = PersistenceValueType.Long,
			["StatPlasmaBlasterKills"] = PersistenceValueType.Long,
			["StatReconSMGKills"] = PersistenceValueType.Long,
			["StatSlagMakerKills"] = PersistenceValueType.Long,
			["StatSkewerKills"] = PersistenceValueType.Long,
			["StatSpikeRevolverKills"] = PersistenceValueType.Long,
			["StatVoltActionKills"] = PersistenceValueType.Long,
			["StatWetworkKills"] = PersistenceValueType.Long,
			["StatArcZapperKills"] = PersistenceValueType.Long,
			["StatSentinelBeamKils"] = PersistenceValueType.Long,
			["StatRocketLaucherKills"] = PersistenceValueType.Long,
			["StatScatterShotKills"] = PersistenceValueType.Long,
			["StatHexWallKills"] = PersistenceValueType.Long,
			["StatKnockBackAbilityKills"] = PersistenceValueType.Long,
			["StatCarbineKills"] = PersistenceValueType.Long,
			["StatSentinelBeamKills"] = PersistenceValueType.Long,
			["StatGrappleHookKills"] = PersistenceValueType.Long,
			["StatGrappleHijackGhosts"] = PersistenceValueType.Long,
			["unsc_datapad_amethyst"] = PersistenceValueType.Byte,
			["unsc_datapad_diamond"] = PersistenceValueType.Byte,
			["unsc_datapad_amber"] = PersistenceValueType.Byte,
			["unsc_datapad_beryl"] = PersistenceValueType.Byte,
			["unsc_datapad_bloodstone"] = PersistenceValueType.Byte,
			["unsc_datapad_carenlian"] = PersistenceValueType.Byte,
			["unsc_datapad_chrysoberyl"] = PersistenceValueType.Byte,
			["unsc_datapad_danburite"] = PersistenceValueType.Byte,
			["unsc_datapad_garnet"] = PersistenceValueType.Byte,
			["unsc_datapad_heliodor"] = PersistenceValueType.Byte,
			["unsc_datapad_jade"] = PersistenceValueType.Byte,
			["unsc_datapad_jadeite"] = PersistenceValueType.Byte,
			["unsc_datapad_kyanite"] = PersistenceValueType.Byte,
			["unsc_datapad_keshi"] = PersistenceValueType.Byte,
			["unsc_datapad_niter"] = PersistenceValueType.Byte,
			["unsc_datapad_olgite"] = PersistenceValueType.Byte,
			["unsc_datapad_petzite"] = PersistenceValueType.Byte,
			["unsc_datapad_quartz"] = PersistenceValueType.Byte,
			["unsc_datapad_jonite"] = PersistenceValueType.Byte,
			["unsc_datapad_brianite"] = PersistenceValueType.Byte,
			["unsc_datapad_paulite"] = PersistenceValueType.Byte,
			["unsc_datapad_joetz"] = PersistenceValueType.Byte,
			["unsc_datapad_troyer"] = PersistenceValueType.Byte,
			["unsc_datapad_jerryite"] = PersistenceValueType.Byte,
			["unsc_datapad_alexyl"] = PersistenceValueType.Byte,
			["unsc_datapad_mulkeyite"] = PersistenceValueType.Byte,
			["unsc_datapad_traugite"] = PersistenceValueType.Byte,
			["unsc_datapad_schmitty"] = PersistenceValueType.Byte,
			["unsc_datapad_diazilpam"] = PersistenceValueType.Byte,
			["unsc_datapad_doughtyx"] = PersistenceValueType.Byte,
			["unsc_datapad_littleskittle"] = PersistenceValueType.Byte,
			["unsc_datapad_shwang"] = PersistenceValueType.Byte,
			["unsc_datapad_kaasade"] = PersistenceValueType.Byte,
			["unsc_datapad_russyx"] = PersistenceValueType.Byte,
			["unsc_datapad_nixilprene"] = PersistenceValueType.Byte,
			["unsc_datapad_gustovan"] = PersistenceValueType.Byte,
			["unsc_datapad_poolenclay"] = PersistenceValueType.Byte,
			["unsc_datapad_wilsonia"] = PersistenceValueType.Byte,
			["unsc_datapad_guntite"] = PersistenceValueType.Byte,
			["unsc_datapad_solava"] = PersistenceValueType.Byte,
			["unsc_datapad_paynetrain"] = PersistenceValueType.Byte,
			["unsc_datapad_gibofitz"] = PersistenceValueType.Byte,
			["unsc_datapad_cuttina"] = PersistenceValueType.Byte,
			["unsc_datapad_tsirlisite"] = PersistenceValueType.Byte,
			["unsc_datapad_ottite"] = PersistenceValueType.Byte,
			["unsc_datapad_bendite"] = PersistenceValueType.Byte,
			["unsc_datapad_enotsite"] = PersistenceValueType.Byte,
			["unsc_datapad_chosenia"] = PersistenceValueType.Byte,
			["unsc_datapad_lindite"] = PersistenceValueType.Byte,
			["unsc_datapad_pepperite"] = PersistenceValueType.Byte,
			["unsc_datapad_magite"] = PersistenceValueType.Byte,
			["unsc_datapad_murtite"] = PersistenceValueType.Byte,
			["unsc_datapad_orangedin"] = PersistenceValueType.Byte,
			["unsc_datapad_yeticon"] = PersistenceValueType.Byte,
			["unsc_datapad_emojipam"] = PersistenceValueType.Byte,
			["unsc_datapad_skizzle"] = PersistenceValueType.Byte,
			["unsc_datapad_skazzle"] = PersistenceValueType.Byte,
			["unsc_datapad_juicyboose"] = PersistenceValueType.Byte,
			["unsc_datapad_dartsum"] = PersistenceValueType.Byte,
			["unsc_datapad_klim"] = PersistenceValueType.Byte,
			["unsc_datapad_entsniv"] = PersistenceValueType.Byte,
			["unsc_datapad_pogchamp"] = PersistenceValueType.Byte,
			["unsc_datapad_pumpernickle"] = PersistenceValueType.Byte,
			["unsc_datapad_jax"] = PersistenceValueType.Byte,
			["unsc_datapad_zeus"] = PersistenceValueType.Byte,
			["unsc_datapad_hera"] = PersistenceValueType.Byte,
			["unsc_datapad_poseidon"] = PersistenceValueType.Byte,
			["unsc_datapad_demeter"] = PersistenceValueType.Byte,
			["unsc_datapad_athena"] = PersistenceValueType.Byte,
			["unsc_datapad_apollo"] = PersistenceValueType.Byte,
			["unsc_datapad_artemis"] = PersistenceValueType.Byte,
			["unsc_datapad_ares"] = PersistenceValueType.Byte,
			["unsc_datapad_hephaestus"] = PersistenceValueType.Byte,
			["unsc_datapad_aphrodite"] = PersistenceValueType.Byte,
			["unsc_datapad_hermes"] = PersistenceValueType.Byte,
			["unsc_datapad_dionysus"] = PersistenceValueType.Byte,
			["ban_datapad_alexandrite"] = PersistenceValueType.Byte,
			["ban_datapad_ametrine"] = PersistenceValueType.Byte,
			["ban_datapad_basra"] = PersistenceValueType.Byte,
			["ban_datapad_burmese"] = PersistenceValueType.Byte,
			["ban_datapad_citrine"] = PersistenceValueType.Byte,
			["ban_datapad_chrysocolla"] = PersistenceValueType.Byte,
			["ban_datapad_emerald"] = PersistenceValueType.Byte,
			["ban_datapad_fluorite"] = PersistenceValueType.Byte,
			["ban_datapad_hessonite"] = PersistenceValueType.Byte,
			["ban_datapad_iolite"] = PersistenceValueType.Byte,
			["ban_datapad_jasper"] = PersistenceValueType.Byte,
			["ban_datapad_khooni"] = PersistenceValueType.Byte,
			["ban_datapad_kashmir"] = PersistenceValueType.Byte,
			["ban_datapad_kunzite"] = PersistenceValueType.Byte,
			["ban_datapad_rhodonite"] = PersistenceValueType.Byte,
			["ban_datapad_edenite"] = PersistenceValueType.Byte,
			["ban_datapad_faustite"] = PersistenceValueType.Byte,
			["ban_datapad_bazzite"] = PersistenceValueType.Byte,
			["ban_datapad_grossite"] = PersistenceValueType.Byte,
			["ban_datapad_hopeite"] = PersistenceValueType.Byte,
			["ban_datapad_iron"] = PersistenceValueType.Byte,
			["ban_datapad_lead"] = PersistenceValueType.Byte,
			["ban_datapad_mixite"] = PersistenceValueType.Byte,
			["ban_datapad_majorite"] = PersistenceValueType.Byte,
			["ban_datapad_raspite"] = PersistenceValueType.Byte,
			["ban_datapad_spinel"] = PersistenceValueType.Byte,
			["ban_datapad_silver"] = PersistenceValueType.Byte,
			["ban_datapad_sulfur"] = PersistenceValueType.Byte,
			["core_angelfood"] = PersistenceValueType.Byte,
			["core_beignet"] = PersistenceValueType.Byte,
			["core_cannoli"] = PersistenceValueType.Byte,
			["core_danish"] = PersistenceValueType.Byte,
			["core_empanada"] = PersistenceValueType.Byte,
			["core_fritter"] = PersistenceValueType.Byte,
			["core_gingerbread"] = PersistenceValueType.Byte,
			["core_honeycomb"] = PersistenceValueType.Byte,
			["core_jellyroll"] = PersistenceValueType.Byte,
			["core_keylime"] = PersistenceValueType.Byte,
			["core_muffin"] = PersistenceValueType.Byte,
			["core_pancake"] = PersistenceValueType.Byte,
			["core_strudel"] = PersistenceValueType.Byte,
			["core_turnover"] = PersistenceValueType.Byte,
			["core_victoria"] = PersistenceValueType.Byte,
			["core_waffle"] = PersistenceValueType.Byte,
			["core_zeppole"] = PersistenceValueType.Byte,
			["core_amandine"] = PersistenceValueType.Byte,
			["core_brownie"] = PersistenceValueType.Byte,
			["core_cake"] = PersistenceValueType.Byte,
			["core_donut"] = PersistenceValueType.Byte,
			["core_eclair"] = PersistenceValueType.Byte,
			["core_fudge"] = PersistenceValueType.Byte,
			["core_gelato"] = PersistenceValueType.Byte,
			["core_haupia"] = PersistenceValueType.Byte,
			["core_icecream"] = PersistenceValueType.Byte,
			["core_jaffa"] = PersistenceValueType.Byte,
			["core_kolache"] = PersistenceValueType.Byte,
			["core_lemonbar"] = PersistenceValueType.Byte,
			["core_mochi"] = PersistenceValueType.Byte,
			["core_napoleon"] = PersistenceValueType.Byte,
			["core_pudding"] = PersistenceValueType.Byte,
			["core_rosette"] = PersistenceValueType.Byte,
			["core_sundae"] = PersistenceValueType.Byte,
			["core_tart"] = PersistenceValueType.Byte,
			["core_waldorf"] = PersistenceValueType.Byte,
			["core_gummyworm"] = PersistenceValueType.Byte,
			["core_hottoddy"] = PersistenceValueType.Byte,
			["core_kitkat"] = PersistenceValueType.Byte,
			["core_stroopwafel"] = PersistenceValueType.Byte,
			["core_shortbread"] = PersistenceValueType.Byte,
			["core_rockcandy"] = PersistenceValueType.Byte,
			["core_meltaway"] = PersistenceValueType.Byte,
			["core_dreampie"] = PersistenceValueType.Byte,
			["core_biscotti"] = PersistenceValueType.Byte,
			["armor_asgard"] = PersistenceValueType.Byte,
			["armor_baldr"] = PersistenceValueType.Byte,
			["armor_bifrost"] = PersistenceValueType.Byte,
			["armor_brokkr"] = PersistenceValueType.Byte,
			["armor_eitri"] = PersistenceValueType.Byte,
			["armor_eostre"] = PersistenceValueType.Byte,
			["armor_fenrir"] = PersistenceValueType.Byte,
			["armor_freya"] = PersistenceValueType.Byte,
			["armor_frigg"] = PersistenceValueType.Byte,
			["armor_ginnungagap"] = PersistenceValueType.Byte,
			["armor_gungnir"] = PersistenceValueType.Byte,
			["armor_heimdall"] = PersistenceValueType.Byte,
			["armor_hel"] = PersistenceValueType.Byte,
			["armor_huginn"] = PersistenceValueType.Byte,
			["armor_jormungandr"] = PersistenceValueType.Byte,
			["armor_leif"] = PersistenceValueType.Byte,
			["armor_loki"] = PersistenceValueType.Byte,
			["armor_midgard"] = PersistenceValueType.Byte,
			["armor_muninn"] = PersistenceValueType.Byte,
			["armor_niflheim"] = PersistenceValueType.Byte,
			["armor_norn"] = PersistenceValueType.Byte,
			["armor_odin"] = PersistenceValueType.Byte,
			["armor_ragnarok"] = PersistenceValueType.Byte,
			["armor_sif"] = PersistenceValueType.Byte,
			["armor_skadi"] = PersistenceValueType.Byte,
			["armor_sleipnir"] = PersistenceValueType.Byte,
			["armor_surt"] = PersistenceValueType.Byte,
			["armor_thor"] = PersistenceValueType.Byte,
			["armor_tyr"] = PersistenceValueType.Byte,
			["armor_valhalla"] = PersistenceValueType.Byte,
			["armor_valkyrie"] = PersistenceValueType.Byte,
			["armor_vanir"] = PersistenceValueType.Byte,
			["armor_vidar"] = PersistenceValueType.Byte,
			["armor_yggdrasil"] = PersistenceValueType.Byte,
			["forerunner_totem_andromeda"] = PersistenceValueType.Byte,
			["forerunner_totem_cancer"] = PersistenceValueType.Byte,
			["forerunner_totem_draco"] = PersistenceValueType.Byte,
			["forerunner_totem_gemini"] = PersistenceValueType.Byte,
			["forerunner_totem_hydra"] = PersistenceValueType.Byte,
			["forerunner_totem_libra"] = PersistenceValueType.Byte,
			["forerunner_totem_mensa"] = PersistenceValueType.Byte,
			["skull_ant"] = PersistenceValueType.Byte,
			["skull_beetle"] = PersistenceValueType.Byte,
			["skull_cockroach"] = PersistenceValueType.Byte,
			["skull_dragonfly"] = PersistenceValueType.Byte,
			["skull_firefly"] = PersistenceValueType.Byte,
			["skull_grub"] = PersistenceValueType.Byte,
			["skull_hornet"] = PersistenceValueType.Byte,
			["skull_inchworm"] = PersistenceValueType.Byte,
			["skull_junebug"] = PersistenceValueType.Byte,
			["skull_katydid"] = PersistenceValueType.Byte,
			["skull_louse"] = PersistenceValueType.Byte,
			["skull_moth"] = PersistenceValueType.Byte,
			["skull_netwing"] = PersistenceValueType.Byte,
			["skull_termite"] = PersistenceValueType.Byte,
			["skull_vespid"] = PersistenceValueType.Byte,
			["spartan_griffin"] = PersistenceValueType.Byte,
			["spartan_makovich"] = PersistenceValueType.Byte,
			["spartan_sorel"] = PersistenceValueType.Byte,
			["spartan_horvath"] = PersistenceValueType.Byte,
			["spartan_vettel"] = PersistenceValueType.Byte,
			["spartan_stone"] = PersistenceValueType.Byte,
			["spartan_kovan"] = PersistenceValueType.Byte,
			["grapple_hook"] = PersistenceValueType.Boolean,
			["unsc_marine_first"] = PersistenceValueType.Boolean,
			["forerunner_totems_first_detect"] = PersistenceValueType.Boolean,
			["forerunner_totems_first_approach"] = PersistenceValueType.Boolean,
			["forerunner_totems_first_scan"] = PersistenceValueType.Boolean,
			["forerunner_totems_second_scan"] = PersistenceValueType.Boolean,
			["forerunner_totems_third_scan"] = PersistenceValueType.Boolean,
			["forerunner_totems_fourth_scan"] = PersistenceValueType.Boolean,
			["forerunner_totems_fifth_scan"] = PersistenceValueType.Boolean,
			["forerunner_totems_sixth_scan"] = PersistenceValueType.Boolean,
			["forerunner_totems_seventh_scan"] = PersistenceValueType.Boolean,
			["skull_first_detect"] = PersistenceValueType.Boolean,
			["skull_first_pickup"] = PersistenceValueType.Boolean,
			["deadspartan_first_detect"] = PersistenceValueType.Boolean,
			["deadspartan_first_sight"] = PersistenceValueType.Boolean,
			["ban_scanner_first_encounter"] = PersistenceValueType.Boolean,
			["hvt_first_defeated"] = PersistenceValueType.Boolean,
			["fob_first_approach"] = PersistenceValueType.Boolean,
			["unsc_datapad_amber_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_amethyst_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_beryl_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_bloodstone_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_carenlian_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_chrysoberyl_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_danburite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_diamond_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_garnet_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_heliodor_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_jade_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_jadeite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_kyanite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_keshi_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_niter_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_olgite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_petzite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_quartz_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_jonite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_brianite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_paulite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_joetz_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_troyer_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_jerryite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_alexyl_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_mulkeyite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_traugite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_schmitty_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_diazilpam_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_doughtyx_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_littleskittle_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_shwang_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_kaasade_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_russyx_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_nixilprene_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_gustovan_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_poolenclay_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_wilsonia_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_guntite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_solava_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_paynetrain_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_gibofitz_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_cuttina_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_tsirlisite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_ottite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_bendite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_enotsite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_chosenia_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_lindite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_pepperite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_magite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_murtite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_orangedin_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_yeticon_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_emojipam_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_skizzle_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_skazzle_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_juicyboose_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_dartsum_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_klim_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_entsniv_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_pogchamp_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_pumpernickle_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_jax_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_zeus_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_hera_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_poseidon_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_demeter_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_athena_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_apollo_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_artemis_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_ares_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_hephaestus_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_aphrodite_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_hermes_codex_read"] = PersistenceValueType.Boolean,
			["unsc_datapad_dionysus_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_alexandrite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_ametrine_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_basra_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_burmese_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_citrine_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_chrysocolla_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_emerald_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_fluorite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_hessonite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_iolite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_jasper_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_khooni_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_kashmir_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_kunzite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_rhodonite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_edenite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_faustite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_bazzite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_grossite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_hopeite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_iron_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_lead_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_mixite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_majorite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_raspite_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_spinel_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_silver_codex_read"] = PersistenceValueType.Boolean,
			["ban_datapad_sulfur_codex_read"] = PersistenceValueType.Boolean,
			["aluminum_kill_codex_read"] = PersistenceValueType.Boolean,
			["beryllium_kill_codex_read"] = PersistenceValueType.Boolean,
			["cesium_kill_codex_read"] = PersistenceValueType.Boolean,
			["dubnium_kill_codex_read"] = PersistenceValueType.Boolean,
			["einsteinium_kill_codex_read"] = PersistenceValueType.Boolean,
			["fermium_kill_codex_read"] = PersistenceValueType.Boolean,
			["gallium_kill_codex_read"] = PersistenceValueType.Boolean,
			["helium_kill_codex_read"] = PersistenceValueType.Boolean,
			["iridium_kill_codex_read"] = PersistenceValueType.Boolean,
			["lithium_kill_codex_read"] = PersistenceValueType.Boolean,
			["magnesium_kill_codex_read"] = PersistenceValueType.Boolean,
			["nobelium_kill_codex_read"] = PersistenceValueType.Boolean,
			["osmium_kill_codex_read"] = PersistenceValueType.Boolean,
			["plutonium_kill_codex_read"] = PersistenceValueType.Boolean,
			["radium_kill_codex_read"] = PersistenceValueType.Boolean,
			["forerunner_totem_andromeda_codex_read"] = PersistenceValueType.Boolean,
			["forerunner_totem_cancer_codex_read"] = PersistenceValueType.Boolean,
			["forerunner_totem_draco_codex_read"] = PersistenceValueType.Boolean,
			["forerunner_totem_gemini_codex_read"] = PersistenceValueType.Boolean,
			["forerunner_totem_hydra_codex_read"] = PersistenceValueType.Boolean,
			["forerunner_totem_libra_codex_read"] = PersistenceValueType.Boolean,
			["forerunner_totem_mensa_codex_read"] = PersistenceValueType.Boolean,
			["core_angelfood_codex_read"] = PersistenceValueType.Boolean,
			["core_beignet_codex_read"] = PersistenceValueType.Boolean,
			["core_cannoli_codex_read"] = PersistenceValueType.Boolean,
			["core_danish_codex_read"] = PersistenceValueType.Boolean,
			["core_empanada_codex_read"] = PersistenceValueType.Boolean,
			["core_fritter_codex_read"] = PersistenceValueType.Boolean,
			["core_gingerbread_codex_read"] = PersistenceValueType.Boolean,
			["core_honeycomb_codex_read"] = PersistenceValueType.Boolean,
			["core_jellyroll_codex_read"] = PersistenceValueType.Boolean,
			["core_keylime_codex_read"] = PersistenceValueType.Boolean,
			["core_muffin_codex_read"] = PersistenceValueType.Boolean,
			["core_pancake_codex_read"] = PersistenceValueType.Boolean,
			["core_strudel_codex_read"] = PersistenceValueType.Boolean,
			["core_turnover_codex_read"] = PersistenceValueType.Boolean,
			["core_victoria_codex_read"] = PersistenceValueType.Boolean,
			["core_waffle_codex_read"] = PersistenceValueType.Boolean,
			["core_zeppole_codex_read"] = PersistenceValueType.Boolean,
			["core_amandine_codex_read"] = PersistenceValueType.Boolean,
			["core_brownie_codex_read"] = PersistenceValueType.Boolean,
			["core_cake_codex_read"] = PersistenceValueType.Boolean,
			["core_donut_codex_read"] = PersistenceValueType.Boolean,
			["core_eclair_codex_read"] = PersistenceValueType.Boolean,
			["core_fudge_codex_read"] = PersistenceValueType.Boolean,
			["core_gelato_codex_read"] = PersistenceValueType.Boolean,
			["core_haupia_codex_read"] = PersistenceValueType.Boolean,
			["core_icecream_codex_read"] = PersistenceValueType.Boolean,
			["core_jaffa_codex_read"] = PersistenceValueType.Boolean,
			["core_kolache_codex_read"] = PersistenceValueType.Boolean,
			["core_lemonbar_codex_read"] = PersistenceValueType.Boolean,
			["core_mochi_codex_read"] = PersistenceValueType.Boolean,
			["core_napoleon_codex_read"] = PersistenceValueType.Boolean,
			["core_rosette_codex_read"] = PersistenceValueType.Boolean,
			["core_pudding_codex_read"] = PersistenceValueType.Boolean,
			["core_sundae_codex_read"] = PersistenceValueType.Boolean,
			["core_tart_codex_read"] = PersistenceValueType.Boolean,
			["core_waldorf_codex_read"] = PersistenceValueType.Boolean,
			["core_gummyworm_codex_read"] = PersistenceValueType.Boolean,
			["core_hottoddy_codex_read"] = PersistenceValueType.Boolean,
			["core_kitkat_codex_read"] = PersistenceValueType.Boolean,
			["spartan_griffin_codex_read"] = PersistenceValueType.Boolean,
			["spartan_horvath_codex_read"] = PersistenceValueType.Boolean,
			["spartan_makovich_codex_read"] = PersistenceValueType.Boolean,
			["spartan_kovan_codex_read"] = PersistenceValueType.Boolean,
			["spartan_sorel_codex_read"] = PersistenceValueType.Boolean,
			["spartan_stone_codex_read"] = PersistenceValueType.Boolean,
			["spartan_vettel_codex_read"] = PersistenceValueType.Boolean,
			["skull_ant_codex_read"] = PersistenceValueType.Boolean,
			["skull_beetle_codex_read"] = PersistenceValueType.Boolean,
			["skull_cockroach_codex_read"] = PersistenceValueType.Boolean,
			["skull_firefly_codex_read"] = PersistenceValueType.Boolean,
			["skull_grub_codex_read"] = PersistenceValueType.Boolean,
			["skull_hornet_codex_read"] = PersistenceValueType.Boolean,
			["skull_junebug_codex_read"] = PersistenceValueType.Boolean,
			["skull_katydid_codex_read"] = PersistenceValueType.Boolean,
			["skull_louse_codex_read"] = PersistenceValueType.Boolean,
			["skull_moth_codex_read"] = PersistenceValueType.Boolean,
			["skull_netwing_codex_read"] = PersistenceValueType.Boolean,
			["skull_vespid_codex_read"] = PersistenceValueType.Boolean,
			["armor_asgard_codex_read"] = PersistenceValueType.Boolean,
			["armor_baldr_codex_read"] = PersistenceValueType.Boolean,
			["armor_bifrost_codex_read"] = PersistenceValueType.Boolean,
			["armor_brokkr_codex_read"] = PersistenceValueType.Boolean,
			["armor_eitri_codex_read"] = PersistenceValueType.Boolean,
			["armor_eostre_codex_read"] = PersistenceValueType.Boolean,
			["armor_fenrir_codex_read"] = PersistenceValueType.Boolean,
			["armor_frigg_codex_read"] = PersistenceValueType.Boolean,
			["armor_ginnungagap_codex_read"] = PersistenceValueType.Boolean,
			["armor_gungnir_codex_read"] = PersistenceValueType.Boolean,
			["armor_heimdall_codex_read"] = PersistenceValueType.Boolean,
			["armor_hel_codex_read"] = PersistenceValueType.Boolean,
			["armor_huginn_codex_read"] = PersistenceValueType.Boolean,
			["armor_jormungandr_codex_read"] = PersistenceValueType.Boolean,
			["armor_leif_codex_read"] = PersistenceValueType.Boolean,
			["armor_loki_codex_read"] = PersistenceValueType.Boolean,
			["armor_midgard_codex_read"] = PersistenceValueType.Boolean,
			["armor_muninn_codex_read"] = PersistenceValueType.Boolean,
			["armor_niflheim_codex_read"] = PersistenceValueType.Boolean,
			["armor_norn_codex_read"] = PersistenceValueType.Boolean,
			["armor_odin_codex_read"] = PersistenceValueType.Boolean,
			["armor_ragnarok_codex_read"] = PersistenceValueType.Boolean,
			["armor_sif_codex_read"] = PersistenceValueType.Boolean,
			["armor_skadi_codex_read"] = PersistenceValueType.Boolean,
			["armor_sleipnir_codex_read"] = PersistenceValueType.Boolean,
			["armor_surt_codex_read"] = PersistenceValueType.Boolean,
			["armor_thor_codex_read"] = PersistenceValueType.Boolean,
			["armor_tyr_codex_read"] = PersistenceValueType.Boolean,
			["armor_valhalla_codex_read"] = PersistenceValueType.Boolean,
			["armor_valkyrie_codex_read"] = PersistenceValueType.Boolean,
			["armor_vanir_codex_read"] = PersistenceValueType.Boolean,
			["armor_vidar_codex_read"] = PersistenceValueType.Boolean,
			["armor_yggdrasil_codex_read"] = PersistenceValueType.Boolean,
			["first_acquisition_armor_locker"] = PersistenceValueType.Boolean,
			["first_acquisition_game_skull"] = PersistenceValueType.Boolean,
			["first_acquisition_dead_spartan"] = PersistenceValueType.Boolean,
			["first_acquisition_memory_core"] = PersistenceValueType.Boolean,
			["first_acquisition_unsc_datapad"] = PersistenceValueType.Boolean,
			["first_acquisition_ban_datapad"] = PersistenceValueType.Boolean,
			["first_acquisition_halsey_datapad"] = PersistenceValueType.Boolean,
			["first_acquisition_forerunner_totem"] = PersistenceValueType.Boolean,
			["first_acquisition_comm_tower"] = PersistenceValueType.Boolean,
			["hvts_are_read"] = PersistenceValueType.Long,
			["campfire_spawn_id"] = PersistenceValueType.Long,
			["campfire_zone_set_id"] = PersistenceValueType.Long,
			["campfire_map_id"] = PersistenceValueType.Long,
			["campfire_mission_id"] = PersistenceValueType.Long,
			["campfire_objective_count"] = PersistenceValueType.Byte,
			["campfire_golden_path_complete"] = PersistenceValueType.Boolean
		};

		/// <summary>
		/// A subset of all Persistence keys that signifies what should be saved/restored for IL/mid mission purposes
		/// </summary>
		public static readonly string[] ProgressKeys = new[]
		{
			"schematic_evade",
			"schematic_wall",
			"schematic_sensor",
			"Schematic-ShieldUpdgrade1",
			"Schematic-ShieldUpdgrade2",
			"Schematic-ShieldUpdgrade3",
			"poi_base_intro_green",
			"poi_fob_ash",
			"poi_fob_aspen",
			"poi_fob_birch",
			"poi_fob_cedar",
			"poi_fob_cherry",
			"poi_fob_dogwood",
			"poi_fob_elm",
			"poi_fob_magnolia",
			"poi_fob_maple",
			"poi_fob_oak",
			"poi_fob_palm",
			"poi_fob_pecan",
			"poi_fob_pine",
			"poi_fob_redwood",
			"poi_fob_sequoia",
			"poi_fob_spruce",
			"poi_fob_willow",
			"poi_outpost_baboon",
			"poi_outpost_gibbon",
			"poi_outpost_howler",
			"poi_outpost_marmoset",
			"poi_outpost_silverback",
			"poi_outpost_mandrill",
			"poi_outpost_bonobo",
			"poi_unsc_alpha",
			"poi_unsc_bravo",
			"poi_unsc_charlie",
			"poi_unsc_delta",
			"poi_unsc_echo",
			"poi_unsc_foxtrot",
			"poi_unsc_golf",
			"poi_unsc_hotel",
			"poi_unsc_india",
			"poi_unsc_juliet",
			"poi_unsc_kilo",
			"poi_unsc_lima",
			"poi_unsc_mike",
			"poi_unsc_november",
			"poi_unsc_oscar",
			"poi_unsc_papa",
			"poi_unsc_quebec",
			"poi_unsc_romeo",
			"poi_unsc_sierra",
			"poi_unsc_tango",
			"poi_boss_aluminum",
			"poi_boss_beryllium",
			"poi_boss_cesium",
			"poi_boss_dubnium",
			"poi_boss_einsteinium",
			"poi_boss_fermium",
			"poi_boss_gallium",
			"poi_boss_helium",
			"poi_boss_iridium",
			"poi_boss_lithium",
			"poi_boss_magnesium",
			"poi_boss_nobelium",
			"poi_boss_osmium",
			"poi_boss_plutonium",
			"poi_boss_radium",
			"poi_bridge_nail",
			"poi_bridge_staple",
			"poi_bridge_screw",
			"poi_bridge_periwinkle",
			"poi_green_pilot_base",
			"poi_green_refinery",
			"poi_green_prison_island",
			"poi_green_prison",
			"poi_green_spire",
			"poi_yellow_spire",
			"poi_boss_hq_exterior",
			"poi_boss_hq_interior",
			"poi_forerunner_tower_main_mission",
			"poi_forerunner_north",
			"poi_forerunner_south",
			"poi_forerunner_east",
			"poi_forerunner_west",
			"poi_forerunner_dallas",
			"poi_forerunner_houston",
			"poi_forerunner_austin",
			"poi_cortana_palace",
			"poi_scanner_afador",
			"poi_scanner_akbash",
			"poi_scanner_akita",
			"poi_scanner_auggie",
			"poi_scanner_barbet",
			"poi_scanner_bassador",
			"poi_scanner_beagle",
			"poi_scanner_borador",
			"poi_scanner_boxer",
			"poi_scanner_bulldog",
			"poi_scanner_cavador",
			"poi_scanner_chihuahua",
			"poi_scanner_collie",
			"poi_scanner_corgi",
			"poi_scanner_dachshund",
			"poi_scanner_dalmatian",
			"poi_scanner_eurasier",
			"poi_scanner_frenchie",
			"poi_scanner_germanshepherd",
			"poi_scanner_goldenretriever",
			"poi_scanner_goldendoodle",
			"poi_scanner_greatdane",
			"poi_scanner_greyhound",
			"poi_scanner_harrier",
			"poi_scanner_havanese",
			"poi_scanner_horgi",
			"poi_scanner_husky",
			"poi_scanner_jackrussell",
			"poi_scanner_komondor",
			"poi_scanner_labrador",
			"poi_scanner_mastiff",
			"poi_scanner_newfoundland",
			"poi_scanner_otterhound",
			"poi_scanner_peekapoo",
			"poi_scanner_pitbull",
			"poi_scanner_poodle",
			"poi_scanner_pug",
			"poi_scanner_rottweiler",
			"poi_scanner_shihtzu",
			"poi_scanner_shibainu",
			"Dungeon-Underbelly",
			"Dungeon-BanishedShip",
			"dungeon_SeedLost",
			"marmoset_AmmoDump01",
			"marmoset_AmmoDump02",
			"marmoset_AmmoDump03",
			"exampleobjective_01",
			"exampleobjective_02",
			"exampleobjective_03",
			"exampleobjective_04",
			"exampleobjective_05",
			"howler_FreeMarines",
			"howler_FreeMarine01",
			"howler_FreeMarine02",
			"howler_FreeMarine03",
			"howler_FreeVIP",
			"silverback_Investigate",
			"silverback_DestroySilos",
			"silverback_DestroyRepairBays",
			"silverback_Silo01",
			"silverback_Silo02",
			"silverback_Silo03",
			"silverback_Silo04",
			"silverback_RepairBay01",
			"silverback_RepairBay02",
			"green_spire_enter",
			"green_spire_hunters",
			"green_spire_investigate",
			"green_spire_follow_monitor",
			"green_spire_deploy_weapon",
			"green_spire_shutdown",
			"green_spire_defeat_boss",
			"green_spire_observation_room_terminal",
			"green_spire_observation_room_door",
			"green_spire_elevator_started",
			"yellow_spire_goto_top",
			"yellow_spire_shutdown",
			"yellow_spire_enter",
			"yellow_spire_collector_room_terminal",
			"yellow_spire_girders_socket",
			"yellow_spire_observation_terminal",
			"yellow_spire_boss_terminal",
			"gibbon_DestroySilos",
			"gibbon_DestroyRepairBays",
			"gibbon_Silo01",
			"gibbon_Silo02",
			"gibbon_Silo03",
			"gibbon_Silo04",
			"gibbon_Silo05",
			"gibbon_RepairBay01",
			"gibbon_RepairBay02",
			"gibbon_RepairBay03",
			"gibbon_RepairBay04",
			"mandrill_Investigate",
			"mandrill_DisableCrane",
			"mandrill_TransportDestroy",
			"mandrill_RaiseSilos",
			"mandrill_Silo01",
			"bonobo_ClearPath",
			"bonobo_Gate01",
			"bonobo_Gate02",
			"bonobo_Gate03",
			"bonobo_switch_hack",
			"bonobo_destroy_power",
			"alpha_kill",
			"bravo_kill",
			"charlie_kill",
			"delta_kill",
			"echo_kill",
			"foxtrot_kill",
			"golf_kill",
			"hotel_kill",
			"india_kill",
			"juliet_kill",
			"kilo_kill",
			"lima_kill",
			"mike_kill",
			"november_kill",
			"oscar_kill",
			"papa_kill",
			"quebec_kill",
			"romeo_kill",
			"sierra_kill",
			"tango_kill",
			"aluminum_kill",
			"beryllium_kill",
			"cesium_kill",
			"dubnium_kill",
			"einsteinium_kill",
			"fermium_kill",
			"gallium_kill",
			"helium_kill",
			"iridium_kill",
			"lithium_kill",
			"magnesium_kill",
			"nobelium_kill",
			"osmium_kill",
			"plutonium_kill",
			"radium_kill",
			"pilotbase_cylix_seen",
			"pilotbase_reunite",
			"pilotbase_gantry",
			"pilotbase_terminal",
			"pilotbase_murdergate",
			"pilotbase_dock_terminal",
			"pilotbase_dock_pelican",
			"pilotbase_game_finished_vo",
			"pris_island_complete_prison",
			"pris_island_complete_fob",
			"pris_investigate",
			"pris_locate_signal_1",
			"pris_enter_prison",
			"pris_end_lockdown",
			"pris_power_gravlift",
			"pris_fight_reinforcements",
			"pris_loc_sensor",
			"pris_locate_signal_2",
			"pris_rescue_spartan",
			"pris_defeat_chak_lok",
			"prison_bridge",
			"banishedship_DeactivateCannon",
			"banishedship_LocateBridge",
			"banishedship_ScupperShip",
			"banishedship_DestroyManifold_01",
			"banishedship_DestroyManifold_02",
			"banishedship_OverloadEngines",
			"banishedship_EscapeToPelican",
			"banishedship_GrappleToPelican",
			"banishedship_OverrideEngines",
			"banishedship_PingTutorial",
			"banishedship_GrappleTutorial",
			"banishedship_ArmoryTwoDirectivesCompleted",
			"banishedship_BridgeKilledAllEnemies",
			"underbelly_locate_weapon",
			"underbelly_get_index",
			"underbelly_reach_surface",
			"underbelly_investigate_dead_spartan_stone",
			"underbelly_temple_socket",
			"underbelly_temple_terminal",
			"underbelly_defeat_tremonious",
			"underbelly_index_terminal",
			"underbelly_defend_middle_terminal",
			"underbelly_grav_lift_socket",
			"underbelly_temple_bloodgate_and_terminal",
			"underbelly_temple_socket_waypoint",
			"underbelly_temple_cradle_waypoint",
			"underbelly_campfire_cathedral",
			"underbelly_campfire_cortana_exit",
			"underbelly_campfire_temple",
			"refine_goto_refinery",
			"refine_find",
			"refine_descend",
			"refine_disable_laser",
			"refine_overload_regs",
			"refine_interact_regulator_1",
			"refine_disable_regulator_1",
			"refine_disable_cooling_pylons_1_1",
			"refine_disable_cooling_pylons_1_2",
			"refine_interact_regulator_2",
			"refine_disable_regulator_2",
			"refine_disable_cooling_pylons_2_1",
			"refine_disable_cooling_pylons_2_2",
			"refine_com_room_return",
			"refine_disable_laser2",
			"refine_defeat_bassman",
			"refine_goto_laser_hole",
			"refine_goto_dungeon",
			"poi_base_aa_island",
			"aa_island_gun_east",
			"aa_island_gun_east_icon",
			"aa_island_gun_north",
			"aa_island_gun_north_icon",
			"aa_island_gun_west",
			"aa_island_gun_west_icon",
			"aa_island_return_pelican",
			"aa_island_defeat_spartan_killers",
			"aa_island_locate_pilot",
			"boss_hq_exterior_extend_bridge",
			"boss_hq_exterior_exit",
			"boss_hq_interior_challenge_01",
			"boss_hq_interior_challenge_02",
			"boss_hq_interior_reach_03",
			"boss_hq_interior_spartan_killer",
			"boss_hq_interior_boss_time",
			"boss_hq_interior_freedom",
			"boss_hq_interior_hotdog_01",
			"boss_hq_interior_hotdog_02",
			"boss_hq_interior_hotdog_03",
			"boss_hq_interior_hotdog_04",
			"boss_hq_interior_challenge_waypoint",
			"boss_hq_interior_try_free_pilot",
			"cortana_palace_get_to_boss",
			"cortana_palace_retrieve_weapon",
			"cortana_palace_stop_boss",
			"cortana_palace_escape",
			"cortana_palace_judgementroom_elevator",
			"cortana_palace_dropsite_terminal",
			"cortana_palace_entrancehallsaccess_socket",
			"cortana_palace_atrium_terminal",
			"cortana_palace_atrium_exitdoor",
			"cortana_palace_cortana_room_2_terminal",
			"cortana_palace_cortana_room_2_cutscene",
			"cortana_palace_sentinelroom_exitdoor",
			"cortana_palace_cortana_room_3_elevator",
			"cortana_palace_judgmentroom_terminal",
			"poi_fob_aspen_capture",
			"poi_fob_birch_capture",
			"poi_fob_cherry_capture",
			"poi_fob_dogwood_capture",
			"poi_fob_elm_capture",
			"poi_fob_maple_capture",
			"poi_fob_oak_capture",
			"poi_fob_palm_capture",
			"poi_fob_pecan_capture",
			"poi_fob_pine_capture",
			"poi_fob_redwood_capture",
			"poi_fob_sequoia_capture",
			"poi_fob_spruce_capture",
			"poi_fob_willow_capture",
			"nar_towers_initialized",
			"tower_forerunner_north",
			"tower_forerunner_south",
			"tower_forerunner_east",
			"tower_forerunner_west",
			"baboon_EndLockdown",
			"baboon_ExposePanels",
			"baboon_DestroyGenerators",
			"baboon_generator01",
			"baboon_generator02",
			"baboon_generator03",
			"baboon_generator04",
			"baboon_discoveredNarrative",
			"baboon_lockdownNarrative",
			"baboon_commsArrayReinforcements",
			"dallas_digsite_complete",
			"dallas_investigate_conservatory",
			"dallas_investigate_dead_spartan_makovich",
			"dallas_locate_pyre",
			"dallas_survive_ambush",
			"dallas_retrieve_weapon",
			"dallas_investigate_dead_spartan_sorel",
			"dallas_invisible_guilty_a",
			"dallas_invisible_guilty_b_01",
			"dallas_invisible_guilty_b_02",
			"dallas_invisible_guilty_b_all",
			"dallas_elbow_one",
			"dallas_elbow_two",
			"dallas_invisible_drop_down",
			"dallas_invisible_drop_fight_done",
			"dallas_elbow_three",
			"dallas_elbow_four",
			"dallas_conservatory_check",
			"dallas_investigate_cradle",
			"dallas_call_elevator",
			"dallas_invisible_control_elevator_ready",
			"dallas_campfire_observation",
			"dallas_campfire_dropdown",
			"dallas_campfire_ribcage",
			"dallas_elevator_started",
			"dallas_interior",
			"houston_find_entrance",
			"houston_power_gravlift",
			"houston_nexus_south",
			"houston_nexus_west",
			"houston_nexus_north",
			"houston_nexus_east",
			"houston_nexus_terminal_entry",
			"houston_nexus_terminal_end",
			"houston_piston_terminal",
			"houston_gondola_terminal",
			"houston_plaza_terminal",
			"houston_nexus_west_cradle",
			"houston_nexus_north_cradle",
			"houston_nexus_east_cradle",
			"austin_invisible_index_mirrored_plinth",
			"austin_rescue_pilot",
			"austin_escape_dungeon",
			"austin_activate_lift",
			"austin_activate_lift01",
			"austin_activate_lift02",
			"austin_skull_capacitor",
			"austin_find_plinth",
			"austin_invisible_gravlift_a_plinth",
			"austin_invisible_chapel_split",
			"austin_invisible_chapel_east",
			"austin_invisible_chapel_west",
			"austin_invisible_chapel_gravlift",
			"austin_invisible_gravlift_b_plinth",
			"austin_invisible_final",
			"austin_invisible_final_second_door",
			"austin_index_mirrored_plinth_bloodgate",
			"austin_campfire_canopy_vista",
			"austin_campfire_chapel_entry",
			"austin_airlock_entered",
			"poi_periwinkle",
			"aa_island_enter_pelican",
			"periwinkle_houston_arrival",
			"periwinkle_arrival",
			"periwinkle_arrival_plinth_nseq_complete",
			"periwinkle_spire_key",
			"periwinkle_houston_waypoints",
			"periwinkle_houston_return",
			"fr_main_first_key",
			"fr_main_all_keys",
			"fr_main_north_tracker",
			"fr_main_south_tracker",
			"fr_main_east_tracker",
			"fr_main_west_tracker",
			"fr_north_enter_area",
			"fr_north_hack_terminal",
			"fr_north_key_switch",
			"fr_south_enter_area",
			"fr_south_hack_terminal",
			"fr_south_key_switch",
			"fr_east_enter_area",
			"fr_east_hack_terminal",
			"fr_east_key_switch",
			"fr_west_enter_area",
			"fr_west_hack_terminal",
			"fr_west_key_switch",
			"Loadout-IsValid",
			"Loadout-FirstWeaponExists",
			"Loadout-FirstWeaponTag",
			"Loadout-FirstWeaponConfigTag",
			"Loadout-FirstWeaponVariant",
			"Loadout-FirstWeaponAmmoLoaded",
			"Loadout-FirstWeaponTotalAmmo",
			"Loadout-FirstWeaponAge",
			"Loadout-SecondWeaponExists",
			"Loadout-SecondWeaponTag",
			"Loadout-SecondWeaponConfigTag",
			"Loadout-SecondWeaponVariant",
			"Loadout-SecondWeaponAmmoLoaded",
			"Loadout-SecondWeaponTotalAmmo",
			"Loadout-SecondWeaponAge",
			"Loadout-ThirdWeaponExists",
			"Loadout-ThirdWeaponTag",
			"Loadout-ThirdWeaponConfigTag",
			"Loadout-ThirdWeaponVariant",
			"Loadout-ThirdWeaponAmmoLoaded",
			"Loadout-ThirdWeaponTotalAmmo",
			"Loadout-ThirdWeaponAge",
			"Loadout-FourthWeaponExists",
			"Loadout-FourthWeaponTag",
			"Loadout-FourthWeaponConfigTag",
			"Loadout-FourthWeaponVariant",
			"Loadout-FourthWeaponAmmoLoaded",
			"Loadout-FourthWeaponTotalAmmo",
			"Loadout-FourthWeaponAge",
			"Loadout-FirstGrenadeExists",
			"Loadout-FirstGrenadeType",
			"Loadout-FirstGrenadeCount",
			"Loadout-SecondGrenadeExists",
			"Loadout-SecondGrenadeType",
			"Loadout-SecondGrenadeCount",
			"Loadout-ThirdGrenadeExists",
			"Loadout-ThirdGrenadeType",
			"Loadout-ThirdGrenadeCount",
			"Loadout-FourthGrenadeExists",
			"Loadout-FourthGrenadeType",
			"Loadout-FourthGrenadeCount",
			"Loadout-InputSlotsValid",
			"Loadout-FirstInputSlotTag",
			"Loadout-FirstInputSlotEnergy",
			"Loadout-FirstInputSlotEnergyDelay",
			"Loadout-SecondInputSlotTag",
			"Loadout-SecondInputSlotEnergy",
			"Loadout-SecondInputSlotEnergyDelay",
			"Loadout-ThirdInputSlotTag",
			"Loadout-ThirdInputSlotEnergy",
			"Loadout-ThirdInputSlotEnergyDelay",
			"Loadout-SupplyEnergy",
			"tod_current_time",
			"tod_lock_time",
			"nar_ref_extractor_seen",
			"nar_ref_antigonum_hologram_seen",
			"nar_ref_extractor_console_activated",
			"nar_ref_destroyed_pylon_any_base",
			"nar_ref_destroyed_all_plyons_any_base",
			"nar_ref_venting_reset",
			"nar_ref_control_room_console_activated",
			"nar_ref_unscevent_capturedmar_first_seen",
			"nar_ref_mongoose_first_summon",
			"nar_ref_gungoose_first_summon",
			"nar_ref_warthog_first_summon",
			"nar_ref_rockethog_first_summon",
			"nar_ref_rallyhog_first_summon",
			"nar_ref_scorpion_first_summon",
			"nar_ref_wasp_first_summon",
			"FirstVehicleExists",
			"FirstVehicleBSP",
			"FirstVehicleTag",
			"FirstVehicleConfigTag",
			"FirstVehicleVariant",
			"FirstVehicleLocationX",
			"FirstVehicleLocationY",
			"FirstVehicleLocationZ",
			"FirstVehicleFacingX",
			"FirstVehicleFacingY",
			"FirstVehicleFacingZ",
			"SecondVehicleExists",
			"SecondVehicleBSP",
			"SecondVehicleTag",
			"SecondVehicleConfigTag",
			"SecondVehicleVariant",
			"SecondVehicleLocationX",
			"SecondVehicleLocationY",
			"SecondVehicleLocationZ",
			"SecondVehicleFacingX",
			"SecondVehicleFacingY",
			"SecondVehicleFacingZ",
			"Valor-Points",
			"Equipment_Points",
			"Grapple_Upgrade_Level",
			"Evade_Upgrade_Level",
			"Wall_Upgrade_Level",
			"Sensor_Upgrade_Level",
			"Shield_Upgrade_Level",
			"Grapple-Use-Count",
			"Wall-Use-Count",
			"Sensor-Use-Count",
			"Evade-Use-Count",
			"Visor-Use-Count",
			"core_angelfood",
			"core_beignet",
			"core_cannoli",
			"core_danish",
			"core_empanada",
			"core_fritter",
			"core_gingerbread",
			"core_honeycomb",
			"core_jellyroll",
			"core_keylime",
			"core_muffin",
			"core_pancake",
			"core_strudel",
			"core_turnover",
			"core_victoria",
			"core_waffle",
			"core_zeppole",
			"core_amandine",
			"core_brownie",
			"core_cake",
			"core_donut",
			"core_eclair",
			"core_fudge",
			"core_gelato",
			"core_haupia",
			"core_icecream",
			"core_jaffa",
			"core_kolache",
			"core_lemonbar",
			"core_mochi",
			"core_napoleon",
			"core_pudding",
			"core_rosette",
			"core_sundae",
			"core_tart",
			"core_waldorf",
			"core_gummyworm",
			"core_hottoddy",
			"core_kitkat",
			"core_stroopwafel",
			"core_shortbread",
			"core_rockcandy",
			"core_meltaway",
			"core_dreampie",
			"core_biscotti",
			"spartan_griffin",
			"spartan_makovich",
			"spartan_sorel",
			"spartan_horvath",
			"spartan_vettel",
			"spartan_stone",
			"spartan_kovan",
			"grapple_hook",
			"unsc_marine_first",
			"skull_first_detect",
			"skull_first_pickup",
			"deadspartan_first_detect",
			"deadspartan_first_sight",
			"ban_scanner_first_encounter",
			"hvt_first_defeated",
			"fob_first_approach",
			"first_acquisition_armor_locker",
			"first_acquisition_game_skull",
			"first_acquisition_dead_spartan",
			"first_acquisition_memory_core",
			"first_acquisition_unsc_datapad",
			"first_acquisition_ban_datapad",
			"first_acquisition_halsey_datapad",
			"first_acquisition_forerunner_totem",
			"first_acquisition_comm_tower",
			"hvts_are_read",
			"campfire_spawn_id",
			"campfire_zone_set_id",
			"campfire_map_id",
			"campfire_mission_id",
			"campfire_objective_count",
			"campfire_golden_path_complete",
		};
	}    
}
